/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAllUsersParams,
  UploadStoreDataBody,
  UserRoleUpdateRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 상권 데이터를 엑셀로 업로드하여 DB에 저장 및 보정합니다.
 * @summary [관리자] 상점 데이터 엑셀 업로드
 */
export type uploadStoreDataResponse200 = {
  data: Blob
  status: 200
}

export type uploadStoreDataResponse400 = {
  data: Blob
  status: 400
}

export type uploadStoreDataResponse500 = {
  data: Blob
  status: 500
}
    
export type uploadStoreDataResponseSuccess = (uploadStoreDataResponse200) & {
  headers: Headers;
};
export type uploadStoreDataResponseError = (uploadStoreDataResponse400 | uploadStoreDataResponse500) & {
  headers: Headers;
};

export type uploadStoreDataResponse = (uploadStoreDataResponseSuccess | uploadStoreDataResponseError)

export const getUploadStoreDataUrl = () => {


  

  return `/api/admin/stores/upload`
}

export const uploadStoreData = async (uploadStoreDataBody: UploadStoreDataBody, options?: RequestInit): Promise<uploadStoreDataResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadStoreDataBody.file);

  return customFetch<uploadStoreDataResponse>(getUploadStoreDataUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadStoreDataMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext> => {

const mutationKey = ['uploadStoreData'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadStoreData>>, {data: UploadStoreDataBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadStoreData(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadStoreDataMutationResult = NonNullable<Awaited<ReturnType<typeof uploadStoreData>>>
    export type UploadStoreDataMutationBody = UploadStoreDataBody
    export type UploadStoreDataMutationError = Blob

    /**
 * @summary [관리자] 상점 데이터 엑셀 업로드
 */
export const useUploadStoreData = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStoreData>>, TError,{data: UploadStoreDataBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadStoreData>>,
        TError,
        {data: UploadStoreDataBody},
        TContext
      > => {
      return useMutation(getUploadStoreDataMutationOptions(options), queryClient);
    }
    /**
 * 사용자의 권한을 수정합니다.
 * @summary [관리자] 사용자 권한 수정
 */
export type updateUserRoleResponse200 = {
  data: Blob
  status: 200
}

export type updateUserRoleResponse403 = {
  data: Blob
  status: 403
}

export type updateUserRoleResponse404 = {
  data: Blob
  status: 404
}
    
export type updateUserRoleResponseSuccess = (updateUserRoleResponse200) & {
  headers: Headers;
};
export type updateUserRoleResponseError = (updateUserRoleResponse403 | updateUserRoleResponse404) & {
  headers: Headers;
};

export type updateUserRoleResponse = (updateUserRoleResponseSuccess | updateUserRoleResponseError)

export const getUpdateUserRoleUrl = (userId: number,) => {


  

  return `/api/admin/users/${userId}/role`
}

export const updateUserRole = async (userId: number,
    userRoleUpdateRequest: UserRoleUpdateRequest, options?: RequestInit): Promise<updateUserRoleResponse> => {
  
  return customFetch<updateUserRoleResponse>(getUpdateUserRoleUrl(userId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userRoleUpdateRequest,)
  }
);}




export const getUpdateUserRoleMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext> => {

const mutationKey = ['updateUserRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRole>>, {userId: number;data: UserRoleUpdateRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateUserRole(userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRole>>>
    export type UpdateUserRoleMutationBody = UserRoleUpdateRequest
    export type UpdateUserRoleMutationError = Blob

    /**
 * @summary [관리자] 사용자 권한 수정
 */
export const useUpdateUserRole = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserRole>>,
        TError,
        {userId: number;data: UserRoleUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateUserRoleMutationOptions(options), queryClient);
    }
    /**
 * 가입된 모든 사용자를 페이징하여 조회합니다.
 * @summary [관리자] 전체 사용자 목록 조회
 */
export type getAllUsersResponse200 = {
  data: Blob
  status: 200
}

export type getAllUsersResponse403 = {
  data: Blob
  status: 403
}
    
export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
export type getAllUsersResponseError = (getAllUsersResponse403) & {
  headers: Headers;
};

export type getAllUsersResponse = (getAllUsersResponseSuccess | getAllUsersResponseError)

export const getGetAllUsersUrl = (params: GetAllUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/users?${stringifiedParams}` : `/api/admin/users`
}

export const getAllUsers = async (params: GetAllUsersParams, options?: RequestInit): Promise<getAllUsersResponse> => {
  
  return customFetch<getAllUsersResponse>(getGetAllUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllUsersQueryKey = (params?: GetAllUsersParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Blob>(params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = Blob


export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Blob>(
 params: GetAllUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Blob>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Blob>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 전체 사용자 목록 조회
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Blob>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




