/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseListRefreshTokenResponse,
  CommonResponsePageResponseUserResponse,
  CommonResponseString,
  CommonResponseVoid,
  GetAllUsersParams,
  SwaggerErrorResponse,
  UserRoleUpdateRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사용자의 권한을 수정합니다.
 * @summary [관리자] 사용자 권한 수정
 */
export type updateUserRoleResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateUserRoleResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateUserRoleResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateUserRoleResponseSuccess = (updateUserRoleResponse200) & {
  headers: Headers;
};
export type updateUserRoleResponseError = (updateUserRoleResponse403 | updateUserRoleResponse404) & {
  headers: Headers;
};

export type updateUserRoleResponse = (updateUserRoleResponseSuccess | updateUserRoleResponseError)

export const getUpdateUserRoleUrl = (userId: number,) => {


  

  return `/api/admin/users/${userId}/role`
}

export const updateUserRole = async (userId: number,
    userRoleUpdateRequest: UserRoleUpdateRequest, options?: RequestInit): Promise<updateUserRoleResponse> => {
  
  return customFetch<updateUserRoleResponse>(getUpdateUserRoleUrl(userId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userRoleUpdateRequest,)
  }
);}




export const getUpdateUserRoleMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext> => {

const mutationKey = ['updateUserRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRole>>, {userId: number;data: UserRoleUpdateRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateUserRole(userId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRole>>>
    export type UpdateUserRoleMutationBody = UserRoleUpdateRequest
    export type UpdateUserRoleMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 사용자 권한 수정
 */
export const useUpdateUserRole = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRole>>, TError,{userId: number;data: UserRoleUpdateRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserRole>>,
        TError,
        {userId: number;data: UserRoleUpdateRequest},
        TContext
      > => {
      return useMutation(getUpdateUserRoleMutationOptions(options), queryClient);
    }
    /**
 * 가입된 모든 사용자를 페이징하여 조회합니다.
 * @summary [관리자] 전체 사용자 목록 조회
 */
export type getAllUsersResponse200 = {
  data: CommonResponsePageResponseUserResponse
  status: 200
}

export type getAllUsersResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}
    
export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
export type getAllUsersResponseError = (getAllUsersResponse403) & {
  headers: Headers;
};

export type getAllUsersResponse = (getAllUsersResponseSuccess | getAllUsersResponseError)

export const getGetAllUsersUrl = (params: GetAllUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/users?${stringifiedParams}` : `/api/admin/users`
}

export const getAllUsers = async (params: GetAllUsersParams, options?: RequestInit): Promise<getAllUsersResponse> => {
  
  return customFetch<getAllUsersResponse>(getGetAllUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllUsersQueryKey = (params?: GetAllUsersParams,) => {
    return [
    `/api/admin/users`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = SwaggerErrorResponse>(params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = SwaggerErrorResponse


export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = SwaggerErrorResponse>(
 params: GetAllUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = SwaggerErrorResponse>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = SwaggerErrorResponse>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 전체 사용자 목록 조회
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = SwaggerErrorResponse>(
 params: GetAllUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Redis에 저장된 모든 리프레시 토큰을 조회합니다.
 * @summary [관리자] 전체 리프레시 토큰 목록 조회
 */
export type getAllRefreshTokensResponse200 = {
  data: CommonResponseListRefreshTokenResponse
  status: 200
}

export type getAllRefreshTokensResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}
    
export type getAllRefreshTokensResponseSuccess = (getAllRefreshTokensResponse200) & {
  headers: Headers;
};
export type getAllRefreshTokensResponseError = (getAllRefreshTokensResponse403) & {
  headers: Headers;
};

export type getAllRefreshTokensResponse = (getAllRefreshTokensResponseSuccess | getAllRefreshTokensResponseError)

export const getGetAllRefreshTokensUrl = () => {


  

  return `/api/admin/tokens`
}

export const getAllRefreshTokens = async ( options?: RequestInit): Promise<getAllRefreshTokensResponse> => {
  
  return customFetch<getAllRefreshTokensResponse>(getGetAllRefreshTokensUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllRefreshTokensQueryKey = () => {
    return [
    `/api/admin/tokens`
    ] as const;
    }

    
export const getGetAllRefreshTokensQueryOptions = <TData = Awaited<ReturnType<typeof getAllRefreshTokens>>, TError = SwaggerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllRefreshTokensQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRefreshTokens>>> = ({ signal }) => getAllRefreshTokens({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllRefreshTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRefreshTokens>>>
export type GetAllRefreshTokensQueryError = SwaggerErrorResponse


export function useGetAllRefreshTokens<TData = Awaited<ReturnType<typeof getAllRefreshTokens>>, TError = SwaggerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRefreshTokens>>,
          TError,
          Awaited<ReturnType<typeof getAllRefreshTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllRefreshTokens<TData = Awaited<ReturnType<typeof getAllRefreshTokens>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRefreshTokens>>,
          TError,
          Awaited<ReturnType<typeof getAllRefreshTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllRefreshTokens<TData = Awaited<ReturnType<typeof getAllRefreshTokens>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 전체 리프레시 토큰 목록 조회
 */

export function useGetAllRefreshTokens<TData = Awaited<ReturnType<typeof getAllRefreshTokens>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRefreshTokens>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllRefreshTokensQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 특정 사용자의 리프레시 토큰을 조회합니다.
 * @summary [관리자] 특정 사용자 리프레시 토큰 조회
 */
export type getUserRefreshTokenResponse200 = {
  data: CommonResponseString
  status: 200
}

export type getUserRefreshTokenResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type getUserRefreshTokenResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getUserRefreshTokenResponseSuccess = (getUserRefreshTokenResponse200) & {
  headers: Headers;
};
export type getUserRefreshTokenResponseError = (getUserRefreshTokenResponse403 | getUserRefreshTokenResponse404) & {
  headers: Headers;
};

export type getUserRefreshTokenResponse = (getUserRefreshTokenResponseSuccess | getUserRefreshTokenResponseError)

export const getGetUserRefreshTokenUrl = (userId: number,) => {


  

  return `/api/admin/tokens/${userId}`
}

export const getUserRefreshToken = async (userId: number, options?: RequestInit): Promise<getUserRefreshTokenResponse> => {
  
  return customFetch<getUserRefreshTokenResponse>(getGetUserRefreshTokenUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserRefreshTokenQueryKey = (userId?: number,) => {
    return [
    `/api/admin/tokens/${userId}`
    ] as const;
    }

    
export const getGetUserRefreshTokenQueryOptions = <TData = Awaited<ReturnType<typeof getUserRefreshToken>>, TError = SwaggerErrorResponse>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserRefreshTokenQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRefreshToken>>> = ({ signal }) => getUserRefreshToken(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserRefreshTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getUserRefreshToken>>>
export type GetUserRefreshTokenQueryError = SwaggerErrorResponse


export function useGetUserRefreshToken<TData = Awaited<ReturnType<typeof getUserRefreshToken>>, TError = SwaggerErrorResponse>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof getUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRefreshToken<TData = Awaited<ReturnType<typeof getUserRefreshToken>>, TError = SwaggerErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof getUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRefreshToken<TData = Awaited<ReturnType<typeof getUserRefreshToken>>, TError = SwaggerErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 특정 사용자 리프레시 토큰 조회
 */

export function useGetUserRefreshToken<TData = Awaited<ReturnType<typeof getUserRefreshToken>>, TError = SwaggerErrorResponse>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserRefreshTokenQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 특정 사용자의 리프레시 토큰을 삭제하여 강제 로그아웃 시킵니다.
 * @summary [관리자] 특정 사용자 리프레시 토큰 삭제
 */
export type deleteUserRefreshTokenResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteUserRefreshTokenResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteUserRefreshTokenResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteUserRefreshTokenResponseSuccess = (deleteUserRefreshTokenResponse204) & {
  headers: Headers;
};
export type deleteUserRefreshTokenResponseError = (deleteUserRefreshTokenResponse403 | deleteUserRefreshTokenResponse404) & {
  headers: Headers;
};

export type deleteUserRefreshTokenResponse = (deleteUserRefreshTokenResponseSuccess | deleteUserRefreshTokenResponseError)

export const getDeleteUserRefreshTokenUrl = (userId: number,) => {


  

  return `/api/admin/tokens/${userId}`
}

export const deleteUserRefreshToken = async (userId: number, options?: RequestInit): Promise<deleteUserRefreshTokenResponse> => {
  
  return customFetch<deleteUserRefreshTokenResponse>(getDeleteUserRefreshTokenUrl(userId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUserRefreshTokenMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserRefreshToken>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserRefreshToken>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteUserRefreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserRefreshToken>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteUserRefreshToken(userId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserRefreshToken>>>
    
    export type DeleteUserRefreshTokenMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 특정 사용자 리프레시 토큰 삭제
 */
export const useDeleteUserRefreshToken = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserRefreshToken>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserRefreshToken>>,
        TError,
        {userId: number},
        TContext
      > => {
      return useMutation(getDeleteUserRefreshTokenMutationOptions(options), queryClient);
    }
    /**
 * 사용자를 강제 탈퇴시킵니다.
 * @summary [관리자] 사용자 강제 탈퇴
 */
export type deleteUserResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteUserResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteUserResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteUserResponseSuccess = (deleteUserResponse204) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse403 | deleteUserResponse404) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = (userId: number,) => {


  

  return `/api/admin/users/${userId}`
}

export const deleteUser = async (userId: number, options?: RequestInit): Promise<deleteUserResponse> => {
  
  return customFetch<deleteUserResponse>(getDeleteUserUrl(userId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUserMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  deleteUser(userId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 사용자 강제 탈퇴
 */
export const useDeleteUser = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {userId: number},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options), queryClient);
    }
    