/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateEventBody,
  UpdateEventBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 새로운 이벤트를 등록합니다.
 * @summary [관리자] 이벤트 등록
 */
export type createEventResponse201 = {
  data: Blob
  status: 201
}

export type createEventResponse400 = {
  data: Blob
  status: 400
}

export type createEventResponse403 = {
  data: Blob
  status: 403
}
    
export type createEventResponseSuccess = (createEventResponse201) & {
  headers: Headers;
};
export type createEventResponseError = (createEventResponse400 | createEventResponse403) & {
  headers: Headers;
};

export type createEventResponse = (createEventResponseSuccess | createEventResponseError)

export const getCreateEventUrl = () => {


  

  return `/api/admin/events`
}

export const createEvent = async (createEventBody: CreateEventBody, options?: RequestInit): Promise<createEventResponse> => {
  
  return customFetch<createEventResponse>(getCreateEventUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createEventBody,)
  }
);}




export const getCreateEventMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventBody}, TContext> => {

const mutationKey = ['createEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createEvent>>, {data: CreateEventBody}> = (props) => {
          const {data} = props ?? {};

          return  createEvent(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateEventMutationResult = NonNullable<Awaited<ReturnType<typeof createEvent>>>
    export type CreateEventMutationBody = CreateEventBody
    export type CreateEventMutationError = Blob

    /**
 * @summary [관리자] 이벤트 등록
 */
export const useCreateEvent = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createEvent>>, TError,{data: CreateEventBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createEvent>>,
        TError,
        {data: CreateEventBody},
        TContext
      > => {
      return useMutation(getCreateEventMutationOptions(options), queryClient);
    }
    /**
 * 이벤트를 삭제합니다.
 * @summary [관리자] 이벤트 삭제
 */
export type deleteEventResponse204 = {
  data: Blob
  status: 204
}

export type deleteEventResponse403 = {
  data: Blob
  status: 403
}

export type deleteEventResponse404 = {
  data: Blob
  status: 404
}
    
export type deleteEventResponseSuccess = (deleteEventResponse204) & {
  headers: Headers;
};
export type deleteEventResponseError = (deleteEventResponse403 | deleteEventResponse404) & {
  headers: Headers;
};

export type deleteEventResponse = (deleteEventResponseSuccess | deleteEventResponseError)

export const getDeleteEventUrl = (eventId: number,) => {


  

  return `/api/admin/events/${eventId}`
}

export const deleteEvent = async (eventId: number, options?: RequestInit): Promise<deleteEventResponse> => {
  
  return customFetch<deleteEventResponse>(getDeleteEventUrl(eventId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteEventMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['deleteEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEvent>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  deleteEvent(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>
    
    export type DeleteEventMutationError = Blob

    /**
 * @summary [관리자] 이벤트 삭제
 */
export const useDeleteEvent = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEvent>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getDeleteEventMutationOptions(options), queryClient);
    }
    /**
 * 이벤트 정보를 수정합니다.
 * @summary [관리자] 이벤트 수정
 */
export type updateEventResponse200 = {
  data: Blob
  status: 200
}

export type updateEventResponse403 = {
  data: Blob
  status: 403
}

export type updateEventResponse404 = {
  data: Blob
  status: 404
}
    
export type updateEventResponseSuccess = (updateEventResponse200) & {
  headers: Headers;
};
export type updateEventResponseError = (updateEventResponse403 | updateEventResponse404) & {
  headers: Headers;
};

export type updateEventResponse = (updateEventResponseSuccess | updateEventResponseError)

export const getUpdateEventUrl = (eventId: number,) => {


  

  return `/api/admin/events/${eventId}`
}

export const updateEvent = async (eventId: number,
    updateEventBody: UpdateEventBody, options?: RequestInit): Promise<updateEventResponse> => {
  
  return customFetch<updateEventResponse>(getUpdateEventUrl(eventId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEventBody,)
  }
);}




export const getUpdateEventMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventBody}, TContext> => {

const mutationKey = ['updateEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEvent>>, {eventId: number;data: UpdateEventBody}> = (props) => {
          const {eventId,data} = props ?? {};

          return  updateEvent(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>
    export type UpdateEventMutationBody = UpdateEventBody
    export type UpdateEventMutationError = Blob

    /**
 * @summary [관리자] 이벤트 수정
 */
export const useUpdateEvent = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError,{eventId: number;data: UpdateEventBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEvent>>,
        TError,
        {eventId: number;data: UpdateEventBody},
        TContext
      > => {
      return useMutation(getUpdateEventMutationOptions(options), queryClient);
    }
    