/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonResponseVoid,
  SwaggerErrorResponse,
  UploadExcelBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 엑셀 파일을 업로드하여 제휴 혜택 내용을 일괄 수정합니다.
 * @summary [관리자] 제휴 혜택 엑셀 업로드
 */
export type uploadExcelResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type uploadExcelResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type uploadExcelResponse500 = {
  data: SwaggerErrorResponse
  status: 500
}
    
export type uploadExcelResponseSuccess = (uploadExcelResponse200) & {
  headers: Headers;
};
export type uploadExcelResponseError = (uploadExcelResponse400 | uploadExcelResponse500) & {
  headers: Headers;
};

export type uploadExcelResponse = (uploadExcelResponseSuccess | uploadExcelResponseError)

export const getUploadExcelUrl = () => {


  

  return `/api/admin/excel/upload`
}

export const uploadExcel = async (uploadExcelBody: UploadExcelBody, options?: RequestInit): Promise<uploadExcelResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadExcelBody.file);

  return customFetch<uploadExcelResponse>(getUploadExcelUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadExcelMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadExcel>>, TError,{data: UploadExcelBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadExcel>>, TError,{data: UploadExcelBody}, TContext> => {

const mutationKey = ['uploadExcel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadExcel>>, {data: UploadExcelBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadExcel(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadExcelMutationResult = NonNullable<Awaited<ReturnType<typeof uploadExcel>>>
    export type UploadExcelMutationBody = UploadExcelBody
    export type UploadExcelMutationError = SwaggerErrorResponse

    /**
 * @summary [관리자] 제휴 혜택 엑셀 업로드
 */
export const useUploadExcel = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadExcel>>, TError,{data: UploadExcelBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadExcel>>,
        TError,
        {data: UploadExcelBody},
        TContext
      > => {
      return useMutation(getUploadExcelMutationOptions(options), queryClient);
    }
    /**
 * 상점-조직 제휴 혜택 목록을 엑셀 파일로 다운로드합니다.
 * @summary [관리자] 제휴 혜택 엑셀 다운로드
 */
export type downloadExcelResponse200 = {
  data: string
  status: 200
}

export type downloadExcelResponse500 = {
  data: SwaggerErrorResponse
  status: 500
}
    
export type downloadExcelResponseSuccess = (downloadExcelResponse200) & {
  headers: Headers;
};
export type downloadExcelResponseError = (downloadExcelResponse500) & {
  headers: Headers;
};

export type downloadExcelResponse = (downloadExcelResponseSuccess | downloadExcelResponseError)

export const getDownloadExcelUrl = () => {


  

  return `/api/admin/excel/download`
}

export const downloadExcel = async ( options?: RequestInit): Promise<downloadExcelResponse> => {
  
  return customFetch<downloadExcelResponse>(getDownloadExcelUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDownloadExcelQueryKey = () => {
    return [
    `/api/admin/excel/download`
    ] as const;
    }

    
export const getDownloadExcelQueryOptions = <TData = Awaited<ReturnType<typeof downloadExcel>>, TError = SwaggerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadExcelQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadExcel>>> = ({ signal }) => downloadExcel({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadExcelQueryResult = NonNullable<Awaited<ReturnType<typeof downloadExcel>>>
export type DownloadExcelQueryError = SwaggerErrorResponse


export function useDownloadExcel<TData = Awaited<ReturnType<typeof downloadExcel>>, TError = SwaggerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadExcel>>,
          TError,
          Awaited<ReturnType<typeof downloadExcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadExcel<TData = Awaited<ReturnType<typeof downloadExcel>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadExcel>>,
          TError,
          Awaited<ReturnType<typeof downloadExcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadExcel<TData = Awaited<ReturnType<typeof downloadExcel>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 제휴 혜택 엑셀 다운로드
 */

export function useDownloadExcel<TData = Awaited<ReturnType<typeof downloadExcel>>, TError = SwaggerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadExcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadExcelQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




