/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  AdminSignupRequest,
  CommonResponseLoginResponse,
  CommonResponseLong,
  CommonResponseVoid,
  CompleteSocialSignupParams,
  LoginRequest,
  OwnerSignupRequest,
  StudentSignupRequest,
  SwaggerErrorResponse
} from './generated.schemas';



/**
 * 학생 회원을 등록합니다.
 * @summary [학생] 학생 회원가입
 */
export type signupStudentResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type signupStudentResponseSuccess = (signupStudentResponse200) & {
  headers: Headers;
};
;

export type signupStudentResponse = (signupStudentResponseSuccess)

export const getSignupStudentUrl = () => {


  

  return `/api/auth/signup/student`
}

export const signupStudent = async (studentSignupRequest: StudentSignupRequest, options?: RequestInit): Promise<signupStudentResponse> => {
  
  const res = await fetch(getSignupStudentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      studentSignupRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: signupStudentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupStudentResponse
}


/**
 * 점주 회원을 등록합니다.
 * @summary [점주] 점주 회원가입
 */
export type signupOwnerResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type signupOwnerResponseSuccess = (signupOwnerResponse200) & {
  headers: Headers;
};
;

export type signupOwnerResponse = (signupOwnerResponseSuccess)

export const getSignupOwnerUrl = () => {


  

  return `/api/auth/signup/owner`
}

export const signupOwner = async (ownerSignupRequest: OwnerSignupRequest, options?: RequestInit): Promise<signupOwnerResponse> => {
  
  const res = await fetch(getSignupOwnerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ownerSignupRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: signupOwnerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupOwnerResponse
}


/**
 * 관리자 계정을 생성합니다.
 * @summary [관리자] 관리자 회원가입 (테스트용)
 */
export type signupAdminResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type signupAdminResponseSuccess = (signupAdminResponse200) & {
  headers: Headers;
};
;

export type signupAdminResponse = (signupAdminResponseSuccess)

export const getSignupAdminUrl = () => {


  

  return `/api/auth/signup/admin`
}

export const signupAdmin = async (adminSignupRequest: AdminSignupRequest, options?: RequestInit): Promise<signupAdminResponse> => {
  
  const res = await fetch(getSignupAdminUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminSignupRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: signupAdminResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as signupAdminResponse
}


/**
 * RefreshToken으로 AccessToken을 갱신합니다.
 * @summary [공통] 토큰 갱신
 */
export type refreshResponse200 = {
  data: CommonResponseLoginResponse
  status: 200
}

export type refreshResponse401 = {
  data: SwaggerErrorResponse
  status: 401
}

export type refreshResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse401 | refreshResponse404) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const refresh = async ( options?: RequestInit): Promise<refreshResponse> => {
  
  const res = await fetch(getRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: refreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshResponse
}


/**
 * 사용자를 로그아웃 처리합니다.
 * @summary [공통] 로그아웃
 */
export type logoutResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type logoutResponseSuccess = (logoutResponse200) & {
  headers: Headers;
};
;

export type logoutResponse = (logoutResponseSuccess)

export const getLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  const res = await fetch(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: logoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutResponse
}


/**
 * 아이디와 비밀번호로 로그인합니다.
 * @summary [공통] 로그인
 */
export type loginResponse200 = {
  data: CommonResponseLoginResponse
  status: 200
}

export type loginResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type loginResponse401 = {
  data: SwaggerErrorResponse
  status: 401
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse401) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/api/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}


/**
 * 소셜 로그인 후 추가 정보를 입력하여 회원가입을 완료합니다.
 * @summary [공통] 소셜 회원가입 완료
 */
export type completeSocialSignupResponse200 = {
  data: CommonResponseLoginResponse
  status: 200
}

export type completeSocialSignupResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type completeSocialSignupResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type completeSocialSignupResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type completeSocialSignupResponseSuccess = (completeSocialSignupResponse200) & {
  headers: Headers;
};
export type completeSocialSignupResponseError = (completeSocialSignupResponse400 | completeSocialSignupResponse404 | completeSocialSignupResponse409) & {
  headers: Headers;
};

export type completeSocialSignupResponse = (completeSocialSignupResponseSuccess | completeSocialSignupResponseError)

export const getCompleteSocialSignupUrl = (params: CompleteSocialSignupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/complete-social-signup?${stringifiedParams}` : `/api/auth/complete-social-signup`
}

export const completeSocialSignup = async (params: CompleteSocialSignupParams, options?: RequestInit): Promise<completeSocialSignupResponse> => {
  
  const res = await fetch(getCompleteSocialSignupUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: completeSocialSignupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as completeSocialSignupResponse
}


