/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseIssueCouponResponse,
  CommonResponseListCouponResponse,
  CommonResponseListIssueCouponResponse,
  CommonResponseLong,
  CommonResponseString,
  CommonResponseVoid,
  CreateCouponRequest,
  SwaggerErrorResponse,
  UpdateCouponRequest,
  VerifyCouponRequest
} from './generated.schemas';



/**
 * 특정 상점의 모든 쿠폰을 조회합니다.
 * @summary [공통] 상점별 쿠폰 목록 조회
 */
export type getCouponsByStoreResponse200 = {
  data: CommonResponseListCouponResponse
  status: 200
}

export type getCouponsByStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getCouponsByStoreResponseSuccess = (getCouponsByStoreResponse200) & {
  headers: Headers;
};
export type getCouponsByStoreResponseError = (getCouponsByStoreResponse404) & {
  headers: Headers;
};

export type getCouponsByStoreResponse = (getCouponsByStoreResponseSuccess | getCouponsByStoreResponseError)

export const getGetCouponsByStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/coupons`
}

export const getCouponsByStore = async (storeId: number, options?: RequestInit): Promise<getCouponsByStoreResponse> => {
  
  const res = await fetch(getGetCouponsByStoreUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCouponsByStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCouponsByStoreResponse
}


/**
 * 상점의 새로운 쿠폰을 생성합니다.
 * @summary [점주] 쿠폰 생성
 */
export type createCouponResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createCouponResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createCouponResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type createCouponResponseSuccess = (createCouponResponse201) & {
  headers: Headers;
};
export type createCouponResponseError = (createCouponResponse400 | createCouponResponse403 | createCouponResponse404) & {
  headers: Headers;
};

export type createCouponResponse = (createCouponResponseSuccess | createCouponResponseError)

export const getCreateCouponUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/coupons`
}

export const createCoupon = async (storeId: number,
    createCouponRequest: CreateCouponRequest, options?: RequestInit): Promise<createCouponResponse> => {
  
  const res = await fetch(getCreateCouponUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCouponRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCouponResponse
}


/**
 * 손님이 제시한 4자리 코드를 입력하여 사용 처리합니다.
 * @summary [점주] 쿠폰 사용 확인 (코드 검증)
 */
export type verifyCouponResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type verifyCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type verifyCouponResponseSuccess = (verifyCouponResponse200) & {
  headers: Headers;
};
export type verifyCouponResponseError = (verifyCouponResponse404) & {
  headers: Headers;
};

export type verifyCouponResponse = (verifyCouponResponseSuccess | verifyCouponResponseError)

export const getVerifyCouponUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/coupons/verify`
}

export const verifyCoupon = async (storeId: number,
    verifyCouponRequest: VerifyCouponRequest, options?: RequestInit): Promise<verifyCouponResponse> => {
  
  const res = await fetch(getVerifyCouponUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyCouponRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: verifyCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifyCouponResponse
}


/**
 * 매장에서 사용하기 위해 쿠폰을 활성화하고 4자리 코드를 발급받습니다.
 * @summary [학생] 쿠폰 코드 발급
 */
export type activateCouponResponse200 = {
  data: CommonResponseString
  status: 200
}

export type activateCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type activateCouponResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}

export type activateCouponResponse422 = {
  data: SwaggerErrorResponse
  status: 422
}
    
export type activateCouponResponseSuccess = (activateCouponResponse200) & {
  headers: Headers;
};
export type activateCouponResponseError = (activateCouponResponse404 | activateCouponResponse409 | activateCouponResponse422) & {
  headers: Headers;
};

export type activateCouponResponse = (activateCouponResponseSuccess | activateCouponResponseError)

export const getActivateCouponUrl = (customerCouponId: number,) => {


  

  return `/api/my-coupons/${customerCouponId}/activate`
}

export const activateCoupon = async (customerCouponId: number, options?: RequestInit): Promise<activateCouponResponse> => {
  
  const res = await fetch(getActivateCouponUrl(customerCouponId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: activateCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as activateCouponResponse
}


/**
 * 사용자가 쿠폰을 발급받습니다.
 * @summary [학생] 쿠폰 발급
 */
export type issueCouponResponse200 = {
  data: CommonResponseIssueCouponResponse
  status: 200
}

export type issueCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type issueCouponResponse422 = {
  data: SwaggerErrorResponse
  status: 422
}
    
export type issueCouponResponseSuccess = (issueCouponResponse200) & {
  headers: Headers;
};
export type issueCouponResponseError = (issueCouponResponse404 | issueCouponResponse422) & {
  headers: Headers;
};

export type issueCouponResponse = (issueCouponResponseSuccess | issueCouponResponseError)

export const getIssueCouponUrl = (couponId: number,) => {


  

  return `/api/coupons/${couponId}/issue`
}

export const issueCoupon = async (couponId: number, options?: RequestInit): Promise<issueCouponResponse> => {
  
  const res = await fetch(getIssueCouponUrl(couponId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: issueCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as issueCouponResponse
}


/**
 * 쿠폰을 삭제합니다. (본인 상점만 가능)
 * @summary [점주] 쿠폰 삭제
 */
export type deleteCouponResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteCouponResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteCouponResponseSuccess = (deleteCouponResponse204) & {
  headers: Headers;
};
export type deleteCouponResponseError = (deleteCouponResponse403 | deleteCouponResponse404) & {
  headers: Headers;
};

export type deleteCouponResponse = (deleteCouponResponseSuccess | deleteCouponResponseError)

export const getDeleteCouponUrl = (couponId: number,) => {


  

  return `/api/coupons/${couponId}`
}

export const deleteCoupon = async (couponId: number, options?: RequestInit): Promise<deleteCouponResponse> => {
  
  const res = await fetch(getDeleteCouponUrl(couponId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCouponResponse
}


/**
 * 쿠폰 정보를 수정합니다. (본인 상점만 가능)
 * @summary [점주] 쿠폰 수정
 */
export type updateCouponResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateCouponResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateCouponResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateCouponResponseSuccess = (updateCouponResponse200) & {
  headers: Headers;
};
export type updateCouponResponseError = (updateCouponResponse403 | updateCouponResponse404) & {
  headers: Headers;
};

export type updateCouponResponse = (updateCouponResponseSuccess | updateCouponResponseError)

export const getUpdateCouponUrl = (couponId: number,) => {


  

  return `/api/coupons/${couponId}`
}

export const updateCoupon = async (couponId: number,
    updateCouponRequest: UpdateCouponRequest, options?: RequestInit): Promise<updateCouponResponse> => {
  
  const res = await fetch(getUpdateCouponUrl(couponId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCouponRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateCouponResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCouponResponse
}


/**
 * 사용자가 발급받은 쿠폰 목록을 조회합니다.
 * @summary [학생] 내 쿠폰 조회
 */
export type getMyCouponsResponse200 = {
  data: CommonResponseListIssueCouponResponse
  status: 200
}
    
export type getMyCouponsResponseSuccess = (getMyCouponsResponse200) & {
  headers: Headers;
};
;

export type getMyCouponsResponse = (getMyCouponsResponseSuccess)

export const getGetMyCouponsUrl = () => {


  

  return `/api/my-coupons`
}

export const getMyCoupons = async ( options?: RequestInit): Promise<getMyCouponsResponse> => {
  
  const res = await fetch(getGetMyCouponsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMyCouponsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyCouponsResponse
}


/**
 * 특정 상품에 적용 가능한 쿠폰 목록을 조회합니다.
 * @summary [공통] 상품별 적용 가능 쿠폰 조회
 */
export type getCouponsByItemResponse200 = {
  data: CommonResponseListCouponResponse
  status: 200
}

export type getCouponsByItemResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getCouponsByItemResponseSuccess = (getCouponsByItemResponse200) & {
  headers: Headers;
};
export type getCouponsByItemResponseError = (getCouponsByItemResponse404) & {
  headers: Headers;
};

export type getCouponsByItemResponse = (getCouponsByItemResponseSuccess | getCouponsByItemResponseError)

export const getGetCouponsByItemUrl = (itemId: number,) => {


  

  return `/api/items/${itemId}/coupons`
}

export const getCouponsByItem = async (itemId: number, options?: RequestInit): Promise<getCouponsByItemResponse> => {
  
  const res = await fetch(getGetCouponsByItemUrl(itemId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCouponsByItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCouponsByItemResponse
}


