/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseLong,
  CommonResponsePageResponseFavoriteStoreResponse,
  CommonResponseVoid,
  GetMyFavoritesParams,
  SwaggerErrorResponse
} from './generated.schemas';



/**
 * 특정 상점을 단골 상점으로 등록합니다.
 * @summary [학생] 상점 즐겨찾기 추가
 */
export type addFavoriteResponse201 = {
  data: CommonResponseVoid
  status: 201
}

export type addFavoriteResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type addFavoriteResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type addFavoriteResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type addFavoriteResponseSuccess = (addFavoriteResponse201) & {
  headers: Headers;
};
export type addFavoriteResponseError = (addFavoriteResponse400 | addFavoriteResponse404 | addFavoriteResponse409) & {
  headers: Headers;
};

export type addFavoriteResponse = (addFavoriteResponseSuccess | addFavoriteResponseError)

export const getAddFavoriteUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites`
}

export const addFavorite = async (storeId: number, options?: RequestInit): Promise<addFavoriteResponse> => {
  
  const res = await fetch(getAddFavoriteUrl(storeId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addFavoriteResponse
}


/**
 * 단골 상점 등록을 취소합니다.
 * @summary [학생] 상점 즐겨찾기 취소
 */
export type removeFavoriteResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type removeFavoriteResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type removeFavoriteResponseSuccess = (removeFavoriteResponse204) & {
  headers: Headers;
};
export type removeFavoriteResponseError = (removeFavoriteResponse404) & {
  headers: Headers;
};

export type removeFavoriteResponse = (removeFavoriteResponseSuccess | removeFavoriteResponseError)

export const getRemoveFavoriteUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites`
}

export const removeFavorite = async (storeId: number, options?: RequestInit): Promise<removeFavoriteResponse> => {
  
  const res = await fetch(getRemoveFavoriteUrl(storeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeFavoriteResponse
}


/**
 * 특정 상점의 총 단골 수를 조회합니다.
 * @summary [공통] 상점 즐겨찾기 수 조회
 */
export type countFavoritesResponse200 = {
  data: CommonResponseLong
  status: 200
}

export type countFavoritesResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type countFavoritesResponseSuccess = (countFavoritesResponse200) & {
  headers: Headers;
};
export type countFavoritesResponseError = (countFavoritesResponse404) & {
  headers: Headers;
};

export type countFavoritesResponse = (countFavoritesResponseSuccess | countFavoritesResponseError)

export const getCountFavoritesUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/favorites/count`
}

export const countFavorites = async (storeId: number, options?: RequestInit): Promise<countFavoritesResponse> => {
  
  const res = await fetch(getCountFavoritesUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: countFavoritesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as countFavoritesResponse
}


/**
 * 내가 등록한 단골 상점 목록을 페이징하여 조회합니다.
 * @summary [학생] 내 단골 상점 목록 조회
 */
export type getMyFavoritesResponse200 = {
  data: CommonResponsePageResponseFavoriteStoreResponse
  status: 200
}
    
export type getMyFavoritesResponseSuccess = (getMyFavoritesResponse200) & {
  headers: Headers;
};
;

export type getMyFavoritesResponse = (getMyFavoritesResponseSuccess)

export const getGetMyFavoritesUrl = (params: GetMyFavoritesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/favorites?${stringifiedParams}` : `/api/favorites`
}

export const getMyFavorites = async (params: GetMyFavoritesParams, options?: RequestInit): Promise<getMyFavoritesResponse> => {
  
  const res = await fetch(getGetMyFavoritesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMyFavoritesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyFavoritesResponse
}


