/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
export interface UpdateStudentProfileRequest {
  nickname?: string;
  collegeId?: number;
  departmentId?: number;
  isClubMember?: boolean;
}

export interface ErrorDetail {
  field?: string;
  value?: string;
  reason?: string;
}

export interface ErrorResponse {
  timestamp?: string;
  path?: string;
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

/**
 * 공통 에러 응답
 */
export interface SwaggerErrorResponse {
  /** 성공 여부 */
  isSuccess?: boolean;
  data?: ErrorResponse;
}

export type CommonResponseVoidData = { [key: string]: unknown };

export interface CommonResponseVoid {
  isSuccess?: boolean;
  data?: CommonResponseVoidData;
}

export interface CreateUniversityRequest {
  name: string;
  emailDomain: string;
}

export interface CommonResponseLong {
  isSuccess?: boolean;
  data?: number;
}

export type CreateOrganizationRequestCategory = typeof CreateOrganizationRequestCategory[keyof typeof CreateOrganizationRequestCategory];


export const CreateOrganizationRequestCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface CreateOrganizationRequest {
  category: CreateOrganizationRequestCategory;
  name: string;
  parentId?: number;
  expiresAt?: string;
}

export type StoreCreateRequestStoreCategoriesItem = typeof StoreCreateRequestStoreCategoriesItem[keyof typeof StoreCreateRequestStoreCategoriesItem];


export const StoreCreateRequestStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type StoreCreateRequestStoreMoodsItem = typeof StoreCreateRequestStoreMoodsItem[keyof typeof StoreCreateRequestStoreMoodsItem];


export const StoreCreateRequestStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export interface StoreCreateRequest {
  name: string;
  bizRegNo: string;
  roadAddress: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  storePhone?: string;
  introduction?: string;
  operatingHours?: string;
  storeCategories: StoreCreateRequestStoreCategoriesItem[];
  storeMoods?: StoreCreateRequestStoreMoodsItem[];
  universityIds?: number[];
}

export interface CreateReviewRequest {
  content: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  parentReviewId?: number;
}

export type StoreReportRequestReasonsItem = typeof StoreReportRequestReasonsItem[keyof typeof StoreReportRequestReasonsItem];


export const StoreReportRequestReasonsItem = {
  BENEFIT_REFUSAL: 'BENEFIT_REFUSAL',
  BENEFIT_MISMATCH: 'BENEFIT_MISMATCH',
  EVENT_NOT_HELD: 'EVENT_NOT_HELD',
  CLOSED_OR_MOVED: 'CLOSED_OR_MOVED',
  INFO_ERROR: 'INFO_ERROR',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH',
  ETC: 'ETC',
} as const;

export interface StoreReportRequest {
  reasons: StoreReportRequestReasonsItem[];
  detail?: string;
}

/**
 * 가게 소식 생성 요청
 */
export interface CreateStoreNewsRequest {
  /** 소식 제목 */
  title: string;
  /** 소식 내용 */
  content: string;
}

export type CreateItemRequestBadge = typeof CreateItemRequestBadge[keyof typeof CreateItemRequestBadge];


export const CreateItemRequestBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
} as const;

export interface CreateItemRequest {
  name: string;
  /** @minimum 0 */
  price?: number;
  description?: string;
  itemOrder?: number;
  badge?: CreateItemRequestBadge;
  itemCategoryId?: number;
  hidden?: boolean;
  soldOut?: boolean;
  representative?: boolean;
}

export type CreateCouponRequestBenefitType = typeof CreateCouponRequestBenefitType[keyof typeof CreateCouponRequestBenefitType];


export const CreateCouponRequestBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export type CreateCouponRequestStatus = typeof CreateCouponRequestStatus[keyof typeof CreateCouponRequestStatus];


export const CreateCouponRequestStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED',
} as const;

export interface CreateCouponRequest {
  title: string;
  description?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  totalQuantity: number;
  limitPerUser: number;
  benefitType: CreateCouponRequestBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  status?: CreateCouponRequestStatus;
}

export interface VerifyCouponRequest {
  /**
   * @minLength 4
   * @maxLength 4
   */
  code: string;
}

/**
 * 소식 댓글 생성 요청
 */
export interface CreateStoreNewsCommentRequest {
  /**
   * 댓글 내용
   * @minLength 1
   * @maxLength 500
   */
  content: string;
}

export interface StoreClaimRequest {
  storeId: number;
  userId: number;
  bizRegNo: string;
  representativeName: string;
  storeName: string;
  storePhone?: string;
}

export type ReportRequestReason = typeof ReportRequestReason[keyof typeof ReportRequestReason];


export const ReportRequestReason = {
  MALICIOUS_SLANDER: 'MALICIOUS_SLANDER',
  INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
  RIGHTS_VIOLATION: 'RIGHTS_VIOLATION',
  PRIVACY_INFRINGEMENT: 'PRIVACY_INFRINGEMENT',
  COMMERCIAL_PROMOTION: 'COMMERCIAL_PROMOTION',
  FRAUDULENT_REVIEW: 'FRAUDULENT_REVIEW',
  IRRELEVANT: 'IRRELEVANT',
  OTHER: 'OTHER',
} as const;

export interface ReportRequest {
  reason: ReportRequestReason;
  /**
   * @minLength 0
   * @maxLength 300
   */
  detail?: string;
}

export interface UpdateUniversityRequest {
  universityId: number;
}

export interface ChangeUsernameRequest {
  newUsername: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface CommonResponseString {
  isSuccess?: boolean;
  data?: string;
}

export type CreateInquiryRequestType = typeof CreateInquiryRequestType[keyof typeof CreateInquiryRequestType];


export const CreateInquiryRequestType = {
  COUPON_BENEFIT: 'COUPON_BENEFIT',
  MAP_LOCATION: 'MAP_LOCATION',
  STORE_INFO_ERROR: 'STORE_INFO_ERROR',
  EVENT_PARTICIPATION: 'EVENT_PARTICIPATION',
  ALERT_ACCOUNT: 'ALERT_ACCOUNT',
  PROPOSAL_OTHER: 'PROPOSAL_OTHER',
} as const;

export interface CreateInquiryRequest {
  type: CreateInquiryRequestType;
  /**
   * @minLength 1
   * @maxLength 14
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  content: string;
}

export type IssueCouponResponseStatus = typeof IssueCouponResponseStatus[keyof typeof IssueCouponResponseStatus];


export const IssueCouponResponseStatus = {
  UNUSED: 'UNUSED',
  ACTIVATED: 'ACTIVATED',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
} as const;

export type IssueCouponResponseBenefitType = typeof IssueCouponResponseBenefitType[keyof typeof IssueCouponResponseBenefitType];


export const IssueCouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface IssueCouponResponse {
  studentCouponId?: number;
  couponCode?: string;
  status?: IssueCouponResponseStatus;
  issuedAt?: string;
  expiresAt?: string;
  title?: string;
  description?: string;
  benefitType?: IssueCouponResponseBenefitType;
  benefitValue?: string;
  storeName?: string;
}

export interface CommonResponseIssueCouponResponse {
  isSuccess?: boolean;
  data?: IssueCouponResponse;
}

export interface BizInfo {
  bno?: string;
  pnm?: string;
  b_no?: string;
  start_dt?: string;
  p_nm?: string;
}

export interface BizVerificationRequest {
  bizs?: BizInfo[];
}

export interface Status {
  b_no?: string;
  b_stt?: string;
  b_stt_cd?: string;
}

export interface BizStatus {
  b_no?: string;
  valid?: string;
  valid_msg?: string;
  status?: Status;
}

export interface BizVerificationResponse {
  data?: BizStatus[];
  status_code?: string;
  match_cnt?: number;
  request_cnt?: number;
}

export interface CommonResponseBizVerificationResponse {
  isSuccess?: boolean;
  data?: BizVerificationResponse;
}

export type StudentSignupRequestGender = typeof StudentSignupRequestGender[keyof typeof StudentSignupRequestGender];


export const StudentSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface StudentSignupRequest {
  username?: string;
  password?: string;
  email?: string;
  nickname?: string;
  gender?: StudentSignupRequestGender;
  birthDate?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
}

export type OwnerSignupRequestGender = typeof OwnerSignupRequestGender[keyof typeof OwnerSignupRequestGender];


export const OwnerSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface OwnerSignupRequest {
  username?: string;
  password?: string;
  email?: string;
  gender?: OwnerSignupRequestGender;
  birthDate?: string;
  name?: string;
}

export interface CouncilSignupRequest {
  username?: string;
  password?: string;
  name?: string;
  universityId?: number;
}

export interface LoginResponse {
  accessToken?: string;
  expiresIn?: number;
}

export interface CommonResponseLoginResponse {
  isSuccess?: boolean;
  data?: LoginResponse;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

export interface VerifyEmailCodeRequest {
  email: string;
  code: string;
}

export interface FindPasswordSendCodeRequest {
  username: string;
  email: string;
}

export interface ResetPasswordRequest {
  resetToken: string;
  newPassword: string;
}

export interface SendEmailCodeRequest {
  email: string;
  universityId?: number;
}

export type CompleteSocialSignupRequestRole = typeof CompleteSocialSignupRequestRole[keyof typeof CompleteSocialSignupRequestRole];


export const CompleteSocialSignupRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export type CompleteSocialSignupRequestGender = typeof CompleteSocialSignupRequestGender[keyof typeof CompleteSocialSignupRequestGender];


export const CompleteSocialSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface CompleteSocialSignupRequest {
  role?: CompleteSocialSignupRequestRole;
  gender?: CompleteSocialSignupRequestGender;
  birthDate?: string;
  nickname?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  name?: string;
  email?: string;
}

export interface CreatePartnershipRequest {
  storeId: number;
  organizationId: number;
  benefit: string;
  startsAt: string;
  endsAt: string;
}

export interface StoreClaimRejectionRequest {
  reason?: string;
}

/**
 * 이벤트 타입 목록
 */
export type CreateEventRequestEventTypesItem = typeof CreateEventRequestEventTypesItem[keyof typeof CreateEventRequestEventTypesItem];


export const CreateEventRequestEventTypesItem = {
  FOOD_EVENT: 'FOOD_EVENT',
  POPUP_STORE: 'POPUP_STORE',
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  COMMUNITY: 'COMMUNITY',
} as const;

/**
 * 이벤트 생성 요청
 */
export interface CreateEventRequest {
  /** 이벤트 제목 */
  title: string;
  /** 이벤트 설명 */
  description?: string;
  /** 이벤트 타입 목록 */
  eventTypes: CreateEventRequestEventTypesItem[];
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /** 이벤트 시작일시 */
  startDateTime: string;
  /** 이벤트 종료일시 */
  endDateTime: string;
  /** 대학교 ID */
  universityId: number;
}

/**
 * 학교 이메일 도메인
 */
export interface JsonNullableString {
  present?: boolean;
}

/**
 * 영업 중지 여부
 */
export interface JsonNullableBoolean {
  present?: boolean;
}

/**
 * 경도
 */
export interface JsonNullableDouble {
  present?: boolean;
}

/**
 * 휴무일 목록
 */
export interface JsonNullableListLocalDate {
  present?: boolean;
}

/**
 * 가게 카테고리 목록
 */
export interface JsonNullableListStoreCategory {
  present?: boolean;
}

/**
 * 가게 분위기 목록
 */
export interface JsonNullableListStoreMood {
  present?: boolean;
}

/**
 * 가게 정보 수정 요청
 */
export interface StoreUpdateRequest {
  name?: JsonNullableString;
  branch?: JsonNullableString;
  roadAddress?: JsonNullableString;
  jibunAddress?: JsonNullableString;
  latitude?: JsonNullableDouble;
  longitude?: JsonNullableDouble;
  phone?: JsonNullableString;
  introduction?: JsonNullableString;
  operatingHours?: JsonNullableString;
  storeCategories?: JsonNullableListStoreCategory;
  storeMoods?: JsonNullableListStoreMood;
  holidayDates?: JsonNullableListLocalDate;
  isSuspended?: JsonNullableBoolean;
}

/**
 * 가게 소식 수정 요청
 */
export interface UpdateStoreNewsRequest {
  title?: JsonNullableString;
  content?: JsonNullableString;
}

/**
 * 별점 (1~5)
 */
export interface JsonNullableInteger {
  present?: boolean;
}

/**
 * 리뷰 수정 요청
 */
export interface UpdateReviewRequest {
  content?: JsonNullableString;
  rating?: JsonNullableInteger;
}

/**
 * 만료 일시
 */
export interface JsonNullableLocalDateTime {
  present?: boolean;
}

/**
 * 상위 조직 ID (예: 단과대 ID)
 */
export interface JsonNullableLong {
  present?: boolean;
}

/**
 * 조직 카테고리 (COLLEGE, DEPARTMENT 등)
 */
export interface JsonNullableOrganizationCategory {
  present?: boolean;
}

/**
 * 조직(단과대/학과 등) 수정 요청
 */
export interface UpdateOrganizationRequest {
  category?: JsonNullableOrganizationCategory;
  name?: JsonNullableString;
  parentId?: JsonNullableLong;
  expiresAt?: JsonNullableLocalDateTime;
}

/**
 * 뱃지 (NEW, BEST, HOT 등)
 */
export interface JsonNullableItemBadge {
  present?: boolean;
}

/**
 * 메뉴(상품) 수정 요청
 */
export interface UpdateItemRequest {
  name?: JsonNullableString;
  price?: JsonNullableInteger;
  description?: JsonNullableString;
  isSoldOut?: JsonNullableBoolean;
  itemOrder?: JsonNullableInteger;
  isRepresentative?: JsonNullableBoolean;
  isHidden?: JsonNullableBoolean;
  badge?: JsonNullableItemBadge;
  itemCategoryId?: JsonNullableLong;
}

/**
 * 혜택 타입 (DISCOUNT_AMOUNT, DISCOUNT_RATE 등)
 */
export interface JsonNullableCouponBenefitType {
  present?: boolean;
}

/**
 * 쿠폰 상태 (ACTIVE, INACTIVE 등)
 */
export interface JsonNullableCouponStatus {
  present?: boolean;
}

/**
 * 쿠폰 수정 요청
 */
export interface UpdateCouponRequest {
  title?: JsonNullableString;
  description?: JsonNullableString;
  issueStartsAt?: JsonNullableLocalDateTime;
  issueEndsAt?: JsonNullableLocalDateTime;
  totalQuantity?: JsonNullableInteger;
  limitPerUser?: JsonNullableInteger;
  benefitType?: JsonNullableCouponBenefitType;
  benefitValue?: JsonNullableString;
  minOrderAmount?: JsonNullableInteger;
  status?: JsonNullableCouponStatus;
}

export type UserRoleUpdateRequestRole = typeof UserRoleUpdateRequestRole[keyof typeof UserRoleUpdateRequestRole];


export const UserRoleUpdateRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export interface UserRoleUpdateRequest {
  role: UserRoleUpdateRequestRole;
}

/**
 * 제휴 종료일
 */
export interface JsonNullableLocalDate {
  present?: boolean;
}

/**
 * 제휴 정보 수정 요청
 */
export interface UpdatePartnershipRequest {
  benefit?: JsonNullableString;
  startsAt?: JsonNullableLocalDate;
  endsAt?: JsonNullableLocalDate;
}

/**
 * 이벤트 상태
 */
export interface JsonNullableEventStatus {
  present?: boolean;
}

/**
 * 이벤트 타입 목록
 */
export interface JsonNullableListEventType {
  present?: boolean;
}

/**
 * 이벤트 수정 요청
 */
export interface UpdateEventRequest {
  title?: JsonNullableString;
  description?: JsonNullableString;
  eventTypes?: JsonNullableListEventType;
  latitude?: JsonNullableDouble;
  longitude?: JsonNullableDouble;
  startDateTime?: JsonNullableLocalDateTime;
  endDateTime?: JsonNullableLocalDateTime;
  status?: JsonNullableEventStatus;
}

export interface UniversityResponse {
  id?: number;
  name?: string;
  emailDomain?: string;
}

export interface CommonResponseListUniversityResponse {
  isSuccess?: boolean;
  data?: UniversityResponse[];
}

export type OrganizationResponseCategory = typeof OrganizationResponseCategory[keyof typeof OrganizationResponseCategory];


export const OrganizationResponseCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface OrganizationResponse {
  id?: number;
  userId?: number;
  universityId?: number;
  universityName?: string;
  category?: OrganizationResponseCategory;
  name?: string;
  expiresAt?: string;
}

export interface CommonResponseListOrganizationResponse {
  isSuccess?: boolean;
  data?: OrganizationResponse[];
}

export type CouponResponseStatus = typeof CouponResponseStatus[keyof typeof CouponResponseStatus];


export const CouponResponseStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED',
} as const;

export type CouponResponseBenefitType = typeof CouponResponseBenefitType[keyof typeof CouponResponseBenefitType];


export const CouponResponseBenefitType = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  PERCENTAGE_DISCOUNT: 'PERCENTAGE_DISCOUNT',
  SERVICE_GIFT: 'SERVICE_GIFT',
} as const;

export interface CouponResponse {
  id?: number;
  storeId?: number;
  title?: string;
  description?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: CouponResponseStatus;
  benefitType?: CouponResponseBenefitType;
  benefitValue?: string;
  minOrderAmount?: number;
  isIssued?: boolean;
}

export interface CommonResponseListCouponResponse {
  isSuccess?: boolean;
  data?: CouponResponse[];
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export type StoreResponseStoreCategoriesItem = typeof StoreResponseStoreCategoriesItem[keyof typeof StoreResponseStoreCategoriesItem];


export const StoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type StoreResponseStoreMoodsItem = typeof StoreResponseStoreMoodsItem[keyof typeof StoreResponseStoreMoodsItem];


export const StoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type StoreResponseCloverGrade = typeof StoreResponseCloverGrade[keyof typeof StoreResponseCloverGrade];


export const StoreResponseCloverGrade = {
  SEED: 'SEED',
  SPROUT: 'SPROUT',
  THREE_LEAF: 'THREE_LEAF',
} as const;

export interface StoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  branch?: string;
  roadAddress?: string;
  jibunAddress?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  introduction?: string;
  operatingHours?: string;
  needToCheck?: boolean;
  storeCategories?: StoreResponseStoreCategoriesItem[];
  storeMoods?: StoreResponseStoreMoodsItem[];
  imageUrls?: string[];
  averageRating?: number;
  reviewCount?: number;
  holidayDates?: string[];
  isSuspended?: boolean;
  isPartnership?: boolean;
  hasCoupon?: boolean;
  cloverGrade?: StoreResponseCloverGrade;
}

export interface PageResponseStoreResponse {
  content?: StoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreResponse;
}

export interface CommonResponseStoreResponse {
  isSuccess?: boolean;
  data?: StoreResponse;
}

export interface StoreStatsResponse {
  totalRegulars?: number;
  totalIssuedCoupons?: number;
  totalUsedCoupons?: number;
  totalReviews?: number;
}

export interface CommonResponseStoreStatsResponse {
  isSuccess?: boolean;
  data?: StoreStatsResponse;
}

export interface ReviewResponse {
  reviewId?: number;
  storeId?: number;
  storeName?: string;
  parentReviewId?: number;
  username?: string;
  content?: string;
  rating?: number;
  createdAt?: string;
  likeCount?: number;
  imageUrls?: string[];
  ownerReply?: boolean;
}

export interface PageResponseReviewResponse {
  content?: ReviewResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseReviewResponse {
  isSuccess?: boolean;
  data?: PageResponseReviewResponse;
}

export interface ReviewStatsResponse {
  averageRating?: number;
  totalReviews?: number;
  rating1Count?: number;
  rating2Count?: number;
  rating3Count?: number;
  rating4Count?: number;
  rating5Count?: number;
}

export interface CommonResponseReviewStatsResponse {
  isSuccess?: boolean;
  data?: ReviewStatsResponse;
}

export interface StoreRegistrationStatusResponse {
  hasMenu?: boolean;
  hasStoreInfo?: boolean;
}

export interface CommonResponseStoreRegistrationStatusResponse {
  isSuccess?: boolean;
  data?: StoreRegistrationStatusResponse;
}

export interface StoreNewsResponse {
  id?: number;
  storeId?: number;
  title?: string;
  content?: string;
  createdAt?: string;
  imageUrls?: string[];
  likeCount?: number;
  commentCount?: number;
  liked?: boolean;
}

export interface PageResponseStoreNewsResponse {
  content?: StoreNewsResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsResponse;
}

export type ItemResponseBadge = typeof ItemResponseBadge[keyof typeof ItemResponseBadge];


export const ItemResponseBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
} as const;

export interface ItemResponse {
  id?: number;
  storeId?: number;
  name?: string;
  price?: number;
  description?: string;
  imageUrl?: string;
  itemOrder?: number;
  badge?: ItemResponseBadge;
  hidden?: boolean;
  soldOut?: boolean;
  representative?: boolean;
}

export interface CommonResponseListItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse[];
}

export interface ItemCategoryResponse {
  id?: number;
  storeId?: number;
  name?: string;
}

export interface CommonResponseListItemCategoryResponse {
  isSuccess?: boolean;
  data?: ItemCategoryResponse[];
}

export interface CommonResponseListStoreResponse {
  isSuccess?: boolean;
  data?: StoreResponse[];
}

export interface HotStoreResponse {
  storeId?: number;
  name?: string;
  categories?: string[];
  benefitContent?: string;
  favoriteGain?: number;
}

export interface CommonResponseListHotStoreResponse {
  isSuccess?: boolean;
  data?: HotStoreResponse[];
}

export interface CommonResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: StoreNewsResponse;
}

export interface StoreNewsCommentResponse {
  id?: number;
  userId?: number;
  nickname?: string;
  content?: string;
  createdAt?: string;
  mine?: boolean;
}

export interface PageResponseStoreNewsCommentResponse {
  content?: StoreNewsCommentResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsCommentResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsCommentResponse;
}

export type MyStoreClaimResponseStatus = typeof MyStoreClaimResponseStatus[keyof typeof MyStoreClaimResponseStatus];


export const MyStoreClaimResponseStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export interface MyStoreClaimResponse {
  id?: number;
  storeId?: number;
  storeName?: string;
  representativeName?: string;
  status?: MyStoreClaimResponseStatus;
  createdAt?: string;
}

export interface CommonResponseListMyStoreClaimResponse {
  isSuccess?: boolean;
  data?: MyStoreClaimResponse[];
}

export interface StudentInfoResponse {
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  isClubMember?: boolean;
}

export interface CommonResponseStudentInfoResponse {
  isSuccess?: boolean;
  data?: StudentInfoResponse;
}

/**
 * 성별
 */
export type OwnerInfoResponseGender = typeof OwnerInfoResponseGender[keyof typeof OwnerInfoResponseGender];


export const OwnerInfoResponseGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * 점주 정보 응답
 */
export interface OwnerInfoResponse {
  /** 이름 */
  name?: string;
  /** 이메일 */
  email?: string;
  /** 아이디 */
  username?: string;
  /** 성별 */
  gender?: OwnerInfoResponseGender;
  /** 생년월일 */
  birthDate?: string;
}

export interface CommonResponseOwnerInfoResponse {
  isSuccess?: boolean;
  data?: OwnerInfoResponse;
}

export interface CommonResponseListIssueCouponResponse {
  isSuccess?: boolean;
  data?: IssueCouponResponse[];
}

export interface CommonResponseItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse;
}

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
}

export type InquiryResponseType = typeof InquiryResponseType[keyof typeof InquiryResponseType];


export const InquiryResponseType = {
  COUPON_BENEFIT: 'COUPON_BENEFIT',
  MAP_LOCATION: 'MAP_LOCATION',
  STORE_INFO_ERROR: 'STORE_INFO_ERROR',
  EVENT_PARTICIPATION: 'EVENT_PARTICIPATION',
  ALERT_ACCOUNT: 'ALERT_ACCOUNT',
  PROPOSAL_OTHER: 'PROPOSAL_OTHER',
} as const;

export interface InquiryResponse {
  id?: number;
  userId?: number;
  username?: string;
  type?: InquiryResponseType;
  title?: string;
  content?: string;
  imageUrls?: string[];
  createdAt?: string;
}

export interface PageInquiryResponse {
  totalElements?: number;
  totalPages?: number;
  pageable?: PageableObject;
  first?: boolean;
  size?: number;
  content?: InquiryResponse[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  last?: boolean;
  empty?: boolean;
}

export interface CommonResponsePageInquiryResponse {
  isSuccess?: boolean;
  data?: PageInquiryResponse;
}

export interface CommonResponseInquiryResponse {
  isSuccess?: boolean;
  data?: InquiryResponse;
}

export type FavoriteStoreResponseStoreCategoriesItem = typeof FavoriteStoreResponseStoreCategoriesItem[keyof typeof FavoriteStoreResponseStoreCategoriesItem];


export const FavoriteStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export interface FavoriteStoreResponse {
  storeId?: number;
  name?: string;
  roadAddress?: string;
  jibunAddress?: string;
  storeCategories?: FavoriteStoreResponseStoreCategoriesItem[];
  imageUrl?: string;
}

export interface PageResponseFavoriteStoreResponse {
  content?: FavoriteStoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseFavoriteStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseFavoriteStoreResponse;
}

export type EventResponseEventTypesItem = typeof EventResponseEventTypesItem[keyof typeof EventResponseEventTypesItem];


export const EventResponseEventTypesItem = {
  FOOD_EVENT: 'FOOD_EVENT',
  POPUP_STORE: 'POPUP_STORE',
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  COMMUNITY: 'COMMUNITY',
} as const;

export type EventResponseStatus = typeof EventResponseStatus[keyof typeof EventResponseStatus];


export const EventResponseStatus = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export interface EventResponse {
  id?: number;
  title?: string;
  description?: string;
  eventTypes?: EventResponseEventTypesItem[];
  latitude?: number;
  longitude?: number;
  startDateTime?: string;
  endDateTime?: string;
  status?: EventResponseStatus;
  imageUrls?: string[];
  createdAt?: string;
}

export interface PageResponseEventResponse {
  content?: EventResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseEventResponse {
  isSuccess?: boolean;
  data?: PageResponseEventResponse;
}

export interface CommonResponseEventResponse {
  isSuccess?: boolean;
  data?: EventResponse;
}

export interface CommonResponseBoolean {
  isSuccess?: boolean;
  data?: boolean;
}

export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


export const UserResponseRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_COUNCIL: 'ROLE_COUNCIL',
  ROLE_STUDENT: 'ROLE_STUDENT',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export type UserResponseSocialType = typeof UserResponseSocialType[keyof typeof UserResponseSocialType];


export const UserResponseSocialType = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
  KAKAO: 'KAKAO',
  APPLE: 'APPLE',
} as const;

export interface UserResponse {
  id?: number;
  username?: string;
  role?: UserResponseRole;
  socialType?: UserResponseSocialType;
}

export interface PageResponseUserResponse {
  content?: UserResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseUserResponse {
  isSuccess?: boolean;
  data?: PageResponseUserResponse;
}

export type PartnershipResponseCategory = typeof PartnershipResponseCategory[keyof typeof PartnershipResponseCategory];


export const PartnershipResponseCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface PartnershipResponse {
  id?: number;
  organizationId?: number;
  organizationName?: string;
  universityName?: string;
  category?: PartnershipResponseCategory;
  benefit?: string;
  storeId?: number;
  storeName?: string;
}

export interface CommonResponseListPartnershipResponse {
  isSuccess?: boolean;
  data?: PartnershipResponse[];
}

export type StoreClaimResponseStatus = typeof StoreClaimResponseStatus[keyof typeof StoreClaimResponseStatus];


export const StoreClaimResponseStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export interface StoreClaimResponse {
  id?: number;
  storeId?: number;
  userId?: number;
  name?: string;
  storeName?: string;
  bizRegNo?: string;
  representativeName?: string;
  storePhone?: string;
  licenseImageUrl?: string;
  status?: StoreClaimResponseStatus;
  createdAt?: string;
  adminMemo?: string;
}

export interface PageStoreClaimResponse {
  totalElements?: number;
  totalPages?: number;
  pageable?: PageableObject;
  first?: boolean;
  size?: number;
  content?: StoreClaimResponse[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  last?: boolean;
  empty?: boolean;
}

export interface CommonResponsePageStoreClaimResponse {
  isSuccess?: boolean;
  data?: PageStoreClaimResponse;
}

export interface PageResponseInquiryResponse {
  content?: InquiryResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseInquiryResponse {
  isSuccess?: boolean;
  data?: PageResponseInquiryResponse;
}

export type WithdrawRequestReasonsItem = typeof WithdrawRequestReasonsItem[keyof typeof WithdrawRequestReasonsItem];


export const WithdrawRequestReasonsItem = {
  UNUSED: 'UNUSED',
  INSUFFICIENT_BENEFITS: 'INSUFFICIENT_BENEFITS',
  INCONVENIENT: 'INCONVENIENT',
  TOO_MANY_ADS: 'TOO_MANY_ADS',
  NOT_NEEDED: 'NOT_NEEDED',
  OTHER: 'OTHER',
} as const;

export interface WithdrawRequest {
  reasons: WithdrawRequestReasonsItem[];
  detailReason?: string;
}

export type GetStoresParams = {
/**
 * 검색 키워드 (상점 이름)
 */
keyword?: string;
/**
 * 카테고리 필터 (복수 선택 가능)
 */
categories?: GetStoresCategoriesItem[];
/**
 * 분위기 필터 (복수 선택 가능)
 */
moods?: GetStoresMoodsItem[];
/**
 * 대학(상권) ID 필터
 */
universityId?: number;
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type GetStoresCategoriesItem = typeof GetStoresCategoriesItem[keyof typeof GetStoresCategoriesItem];


export const GetStoresCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type GetStoresMoodsItem = typeof GetStoresMoodsItem[keyof typeof GetStoresMoodsItem];


export const GetStoresMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export type CreateStoreBody = {
  /** 상품 이미지 목록 */
  images?: string[];
  request: StoreCreateRequest;
};

export type GetReviewsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CreateReviewBody = {
  request: CreateReviewRequest;
  /** 리뷰 이미지 목록 */
  images?: string[];
};

export type GetStoreNewsListParams = {
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type CreateStoreNewsBody = {
  /** 소식 이미지 목록 */
  images?: string[];
  request: CreateStoreNewsRequest;
};

export type CreateItemBody = {
  /** 상품 이미지 */
  image: string;
  request?: CreateItemRequest;
};

export type CreateItemCategoryBody = {[key: string]: string};

export type GetCommentsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CreateStoreClaimsBody = {
  request: StoreClaimRequest;
  /** 사업자등록증 이미지 */
  image: string;
};

export type GetInquiriesParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CreateInquiryBody = {
  request: CreateInquiryRequest;
  images?: Blob[];
};

export type CompleteSocialSignupParams = {
userId: number;
request: CompleteSocialSignupRequest;
};

export type UploadStoreDataBody = {
  /** 엑셀 파일 (.xlsx) */
  file: Blob;
};

export type UploadPartnershipDataParams = {
/**
 * 대상 조직 ID (관리자용)
 */
organizationId?: number;
};

export type UploadPartnershipDataBody = {
  /** 엑셀 파일 */
  file: Blob;
};

export type CreateEventBody = {
  request: CreateEventRequest;
  /** 이벤트 이미지 */
  images?: string[];
};

export type UpdateStoreBody = {
  request: StoreUpdateRequest;
  images?: string[];
};

export type UpdateItemCategoryBody = {[key: string]: string};

export type UpdateStoreNewsBody = {
  /** 변경할 소식 이미지 목록 */
  images?: string[];
  request: UpdateStoreNewsRequest;
};

export type UpdateReviewBody = {
  request: UpdateReviewRequest;
  /** 리뷰 이미지 목록 */
  images?: string[];
};

export type UpdateItemBody = {
  /** 변경할 상품 이미지 */
  image?: string;
  request?: UpdateItemRequest;
};

export type UpdateEventBody = {
  request: UpdateEventRequest;
  /** 이벤트 이미지 */
  images?: string[];
};

export type HealthCheck200 = {[key: string]: { [key: string]: unknown }};

export type GetNearbyStoresParams = {
/**
 * 위도
 */
latitude: number;
/**
 * 경도
 */
longitude: number;
/**
 * 반경(km)
 */
radius: number;
};

export type SearchUnclaimedStoresParams = {
keyword: string;
};

export type GetMyReviewsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetMyFavoritesParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetEventsParams = {
/**
 * 검색 키워드 (제목)
 */
keyword?: string;
/**
 * 이벤트 타입 필터 (복수 선택 가능)
 */
eventTypes?: GetEventsEventTypesItem[];
/**
 * 상태 필터
 */
status?: GetEventsStatus;
/**
 * 대학 ID
 */
universityId?: number;
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetEventsEventTypesItem = typeof GetEventsEventTypesItem[keyof typeof GetEventsEventTypesItem];


export const GetEventsEventTypesItem = {
  FOOD_EVENT: 'FOOD_EVENT',
  POPUP_STORE: 'POPUP_STORE',
  SCHOOL_EVENT: 'SCHOOL_EVENT',
  FLEA_MARKET: 'FLEA_MARKET',
  PERFORMANCE: 'PERFORMANCE',
  COMMUNITY: 'COMMUNITY',
} as const;

export type GetEventsStatus = typeof GetEventsStatus[keyof typeof GetEventsStatus];


export const GetEventsStatus = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  ENDED: 'ENDED',
} as const;

export type CheckUsernameAvailabilityParams = {
username: string;
};

export type GetAllUsersParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetStoreClaimsParams = {
/**
 * 요청 상태 (PENDING, APPROVED, REJECTED, CANCELED)
 */
status?: GetStoreClaimsStatus;
pageable: Pageable;
};

export type GetStoreClaimsStatus = typeof GetStoreClaimsStatus[keyof typeof GetStoreClaimsStatus];


export const GetStoreClaimsStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
} as const;

export type ExportPartnershipTemplateParams = {
/**
 * 대상 대학 ID
 */
universityId: number;
};

export type GetAllInquiriesParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

