/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
export interface CreateUniversityRequest {
  name: string;
  emailDomain: string;
}

export interface CommonResponseLong {
  isSuccess?: boolean;
  data?: number;
}

export type CreateOrganizationRequestCategory = typeof CreateOrganizationRequestCategory[keyof typeof CreateOrganizationRequestCategory];


export const CreateOrganizationRequestCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface CreateOrganizationRequest {
  category: CreateOrganizationRequestCategory;
  name: string;
  parentId?: number;
  expiresAt?: string;
}

export type CreateStoreRequestStoreCategoriesItem = typeof CreateStoreRequestStoreCategoriesItem[keyof typeof CreateStoreRequestStoreCategoriesItem];


export const CreateStoreRequestStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type CreateStoreRequestStoreMoodsItem = typeof CreateStoreRequestStoreMoodsItem[keyof typeof CreateStoreRequestStoreMoodsItem];


export const CreateStoreRequestStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export interface CreateStoreRequest {
  name: string;
  businessRegistrationNumber: string;
  address: string;
  latitude?: number;
  longitude?: number;
  phoneNumber?: string;
  introduction?: string;
  operatingHours?: string;
  storeCategories: CreateStoreRequestStoreCategoriesItem[];
  storeMoods?: CreateStoreRequestStoreMoodsItem[];
}

export interface ErrorDetail {
  field?: string;
  value?: string;
  reason?: string;
}

export interface ErrorResponse {
  timestamp?: string;
  path?: string;
  code?: string;
  message?: string;
  details?: ErrorDetail[];
}

/**
 * 공통 에러 응답
 */
export interface SwaggerErrorResponse {
  /** 성공 여부 */
  isSuccess?: boolean;
  data?: ErrorResponse;
}

export interface CreateReviewRequest {
  content: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
}

export type StoreReportRequestReasonsItem = typeof StoreReportRequestReasonsItem[keyof typeof StoreReportRequestReasonsItem];


export const StoreReportRequestReasonsItem = {
  BENEFIT_REFUSAL: 'BENEFIT_REFUSAL',
  BENEFIT_MISMATCH: 'BENEFIT_MISMATCH',
  EVENT_NOT_HELD: 'EVENT_NOT_HELD',
  CLOSED_OR_MOVED: 'CLOSED_OR_MOVED',
  INFO_ERROR: 'INFO_ERROR',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH',
  ETC: 'ETC',
} as const;

export interface StoreReportRequest {
  reasons: StoreReportRequestReasonsItem[];
  detail?: string;
}

export type CommonResponseVoidData = { [key: string]: unknown };

export interface CommonResponseVoid {
  isSuccess?: boolean;
  data?: CommonResponseVoidData;
}

export interface CreatePartnershipRequest {
  organizationId: number;
  benefit: string;
}

/**
 * 가게 소식 생성 요청
 */
export interface CreateStoreNewsRequest {
  /** 소식 제목 */
  title: string;
  /** 소식 내용 */
  content: string;
}

export type CreateItemRequestBadge = typeof CreateItemRequestBadge[keyof typeof CreateItemRequestBadge];


export const CreateItemRequestBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
} as const;

export interface CreateItemRequest {
  name: string;
  /** @minimum 0 */
  price?: number;
  description?: string;
  itemOrder?: number;
  badge?: CreateItemRequestBadge;
  hidden?: boolean;
  representative?: boolean;
  soldOut?: boolean;
}

export type CreateCouponRequestStatus = typeof CreateCouponRequestStatus[keyof typeof CreateCouponRequestStatus];


export const CreateCouponRequestStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED',
} as const;

export interface CreateCouponRequest {
  title: string;
  description?: string;
  targetOrganizationId?: number;
  issueStartsAt?: string;
  issueEndsAt?: string;
  totalQuantity: number;
  limitPerUser: number;
  status?: CreateCouponRequestStatus;
  targetItemIds?: number[];
}

export interface VerifyCouponRequest {
  /**
   * @minLength 4
   * @maxLength 4
   */
  code: string;
}

/**
 * 소식 댓글 생성 요청
 */
export interface CreateStoreNewsCommentRequest {
  /**
   * 댓글 내용
   * @minLength 1
   * @maxLength 500
   */
  content: string;
}

export type ReportRequestReason = typeof ReportRequestReason[keyof typeof ReportRequestReason];


export const ReportRequestReason = {
  SPAM: 'SPAM',
  INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT',
  IRRELEVANT: 'IRRELEVANT',
  OTHER: 'OTHER',
} as const;

export interface ReportRequest {
  reason: ReportRequestReason;
  /**
   * @minLength 0
   * @maxLength 300
   */
  detail?: string;
}

export interface CommonResponseString {
  isSuccess?: boolean;
  data?: string;
}

export type IssueCouponResponseStatus = typeof IssueCouponResponseStatus[keyof typeof IssueCouponResponseStatus];


export const IssueCouponResponseStatus = {
  UNUSED: 'UNUSED',
  ACTIVATED: 'ACTIVATED',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
} as const;

export interface IssueCouponResponse {
  customerCouponId?: number;
  couponCode?: string;
  status?: IssueCouponResponseStatus;
  issuedAt?: string;
  expiresAt?: string;
}

export interface CommonResponseIssueCouponResponse {
  isSuccess?: boolean;
  data?: IssueCouponResponse;
}

export type StudentSignupRequestGender = typeof StudentSignupRequestGender[keyof typeof StudentSignupRequestGender];


export const StudentSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface StudentSignupRequest {
  username?: string;
  password?: string;
  nickname?: string;
  gender?: StudentSignupRequestGender;
  birthDate?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
}

export type OwnerSignupRequestGender = typeof OwnerSignupRequestGender[keyof typeof OwnerSignupRequestGender];


export const OwnerSignupRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  UNKNOWN: 'UNKNOWN',
} as const;

export interface StoreCreateRequest {
  name?: string;
  address?: string;
  partnerUniversityId?: number;
  partnerOrganizationIds?: number[];
  businessRegistrationNumber?: string;
}

export interface OwnerSignupRequest {
  username?: string;
  password?: string;
  name?: string;
  email?: string;
  phoneNumber?: string;
  gender?: OwnerSignupRequestGender;
  birthDate?: string;
  storeList?: StoreCreateRequest[];
}

export interface AdminSignupRequest {
  username?: string;
  password?: string;
}

export interface LoginResponse {
  accessToken?: string;
  expiresIn?: number;
}

export interface CommonResponseLoginResponse {
  isSuccess?: boolean;
  data?: LoginResponse;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

export type CompleteSocialSignupRequestRole = typeof CompleteSocialSignupRequestRole[keyof typeof CompleteSocialSignupRequestRole];


export const CompleteSocialSignupRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export interface CompleteSocialSignupRequest {
  role?: CompleteSocialSignupRequestRole;
  name?: string;
  email?: string;
  phoneNumber?: string;
  nickname?: string;
  universityId?: number;
  collegeId?: number;
  departmentId?: number;
  storeList?: StoreCreateRequest[];
}

export interface UpdateUniversityRequest {
  name: string;
  emailDomain: string;
}

export type UpdateStoreRequestStoreCategoriesItem = typeof UpdateStoreRequestStoreCategoriesItem[keyof typeof UpdateStoreRequestStoreCategoriesItem];


export const UpdateStoreRequestStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type UpdateStoreRequestStoreMoodsItem = typeof UpdateStoreRequestStoreMoodsItem[keyof typeof UpdateStoreRequestStoreMoodsItem];


export const UpdateStoreRequestStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export interface UpdateStoreRequest {
  name?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  phoneNumber?: string;
  introduction?: string;
  operatingHours?: string;
  storeCategories?: UpdateStoreRequestStoreCategoriesItem[];
  storeMoods?: UpdateStoreRequestStoreMoodsItem[];
}

export interface UpdatePartnershipRequest {
  benefit: string;
}

/**
 * 가게 소식 수정 요청
 */
export interface UpdateStoreNewsRequest {
  /** 소식 제목 */
  title: string;
  /** 소식 내용 */
  content: string;
}

export interface UpdateReviewRequest {
  content?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
}

export type UpdateOrganizationRequestCategory = typeof UpdateOrganizationRequestCategory[keyof typeof UpdateOrganizationRequestCategory];


export const UpdateOrganizationRequestCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface UpdateOrganizationRequest {
  category: UpdateOrganizationRequestCategory;
  name: string;
  parentId?: number;
  expiresAt?: string;
}

export type UpdateItemRequestBadge = typeof UpdateItemRequestBadge[keyof typeof UpdateItemRequestBadge];


export const UpdateItemRequestBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
} as const;

export interface UpdateItemRequest {
  name?: string;
  price?: number;
  description?: string;
  isSoldOut?: boolean;
  itemOrder?: number;
  isRepresentative?: boolean;
  isHidden?: boolean;
  badge?: UpdateItemRequestBadge;
}

export type UpdateCouponRequestStatus = typeof UpdateCouponRequestStatus[keyof typeof UpdateCouponRequestStatus];


export const UpdateCouponRequestStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED',
} as const;

export interface UpdateCouponRequest {
  title?: string;
  description?: string;
  issueStartsAt?: string;
  issueEndsAt?: string;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: UpdateCouponRequestStatus;
}

export type UserRoleUpdateRequestRole = typeof UserRoleUpdateRequestRole[keyof typeof UserRoleUpdateRequestRole];


export const UserRoleUpdateRequestRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export interface UserRoleUpdateRequest {
  role: UserRoleUpdateRequestRole;
}

export interface UniversityResponse {
  id?: number;
  name?: string;
  emailDomain?: string;
}

export interface CommonResponseListUniversityResponse {
  isSuccess?: boolean;
  data?: UniversityResponse[];
}

export type OrganizationResponseCategory = typeof OrganizationResponseCategory[keyof typeof OrganizationResponseCategory];


export const OrganizationResponseCategory = {
  COLLEGE: 'COLLEGE',
  DEPARTMENT: 'DEPARTMENT',
  STUDENT_COUNCIL: 'STUDENT_COUNCIL',
} as const;

export interface OrganizationResponse {
  id?: number;
  universityId?: number;
  universityName?: string;
  category?: OrganizationResponseCategory;
  name?: string;
  expiresAt?: string;
}

export interface CommonResponseListOrganizationResponse {
  isSuccess?: boolean;
  data?: OrganizationResponse[];
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export type StoreResponseStoreCategoriesItem = typeof StoreResponseStoreCategoriesItem[keyof typeof StoreResponseStoreCategoriesItem];


export const StoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type StoreResponseStoreMoodsItem = typeof StoreResponseStoreMoodsItem[keyof typeof StoreResponseStoreMoodsItem];


export const StoreResponseStoreMoodsItem = {
  SOLO_DINING: 'SOLO_DINING',
  GROUP_GATHERING: 'GROUP_GATHERING',
  LATE_NIGHT: 'LATE_NIGHT',
  ROMANTIC: 'ROMANTIC',
} as const;

export interface StoreResponse {
  id?: number;
  userId?: number;
  name?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  phoneNumber?: string;
  introduction?: string;
  operatingHours?: string;
  storeCategories?: StoreResponseStoreCategoriesItem[];
  storeMoods?: StoreResponseStoreMoodsItem[];
  imageUrls?: string[];
}

export interface PageResponseStoreResponse {
  content?: StoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreResponse;
}

export interface CommonResponseStoreResponse {
  isSuccess?: boolean;
  data?: StoreResponse;
}

export interface ReviewResponse {
  reviewId?: number;
  storeId?: number;
  username?: string;
  content?: string;
  rating?: number;
  createdAt?: string;
  likeCount?: number;
  imageUrls?: string[];
}

export interface PageResponseReviewResponse {
  content?: ReviewResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseReviewResponse {
  isSuccess?: boolean;
  data?: PageResponseReviewResponse;
}

export interface ReviewStatsResponse {
  averageRating?: number;
  totalReviews?: number;
  rating1Count?: number;
  rating2Count?: number;
  rating3Count?: number;
  rating4Count?: number;
  rating5Count?: number;
}

export interface CommonResponseReviewStatsResponse {
  isSuccess?: boolean;
  data?: ReviewStatsResponse;
}

export interface StoreNewsResponse {
  id?: number;
  storeId?: number;
  title?: string;
  content?: string;
  createdAt?: string;
  imageUrls?: string[];
  likeCount?: number;
  commentCount?: number;
  liked?: boolean;
}

export interface PageResponseStoreNewsResponse {
  content?: StoreNewsResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsResponse;
}

export type ItemResponseBadge = typeof ItemResponseBadge[keyof typeof ItemResponseBadge];


export const ItemResponseBadge = {
  BEST: 'BEST',
  NEW: 'NEW',
  HOT: 'HOT',
} as const;

export interface ItemResponse {
  id?: number;
  storeId?: number;
  name?: string;
  price?: number;
  description?: string;
  imageUrl?: string;
  itemOrder?: number;
  badge?: ItemResponseBadge;
  hidden?: boolean;
  representative?: boolean;
  soldOut?: boolean;
}

export interface CommonResponseListItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse[];
}

export type CouponResponseStatus = typeof CouponResponseStatus[keyof typeof CouponResponseStatus];


export const CouponResponseStatus = {
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  ACTIVE: 'ACTIVE',
  STOPPED: 'STOPPED',
  EXPIRED: 'EXPIRED',
} as const;

export interface CouponResponse {
  id?: number;
  storeId?: number;
  title?: string;
  description?: string;
  targetOrganizationId?: number;
  issueStartsAt?: string;
  issueEndsAt?: string;
  totalQuantity?: number;
  limitPerUser?: number;
  status?: CouponResponseStatus;
}

export interface CommonResponseListCouponResponse {
  isSuccess?: boolean;
  data?: CouponResponse[];
}

export interface CommonResponseListStoreResponse {
  isSuccess?: boolean;
  data?: StoreResponse[];
}

export interface CommonResponseStoreNewsResponse {
  isSuccess?: boolean;
  data?: StoreNewsResponse;
}

export interface StoreNewsCommentResponse {
  id?: number;
  userId?: number;
  nickname?: string;
  content?: string;
  createdAt?: string;
  mine?: boolean;
}

export interface PageResponseStoreNewsCommentResponse {
  content?: StoreNewsCommentResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseStoreNewsCommentResponse {
  isSuccess?: boolean;
  data?: PageResponseStoreNewsCommentResponse;
}

export interface CommonResponseListIssueCouponResponse {
  isSuccess?: boolean;
  data?: IssueCouponResponse[];
}

export interface CommonResponseItemResponse {
  isSuccess?: boolean;
  data?: ItemResponse;
}

export type FavoriteStoreResponseStoreCategoriesItem = typeof FavoriteStoreResponseStoreCategoriesItem[keyof typeof FavoriteStoreResponseStoreCategoriesItem];


export const FavoriteStoreResponseStoreCategoriesItem = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export interface FavoriteStoreResponse {
  storeId?: number;
  name?: string;
  address?: string;
  storeCategories?: FavoriteStoreResponseStoreCategoriesItem[];
  imageUrl?: string;
}

export interface PageResponseFavoriteStoreResponse {
  content?: FavoriteStoreResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseFavoriteStoreResponse {
  isSuccess?: boolean;
  data?: PageResponseFavoriteStoreResponse;
}

export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


export const UserResponseRole = {
  ROLE_GUEST: 'ROLE_GUEST',
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_OWNER: 'ROLE_OWNER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;

export type UserResponseSocialType = typeof UserResponseSocialType[keyof typeof UserResponseSocialType];


export const UserResponseSocialType = {
  LOCAL: 'LOCAL',
  GOOGLE: 'GOOGLE',
  NAVER: 'NAVER',
  KAKAO: 'KAKAO',
  FIREBASE: 'FIREBASE',
} as const;

export interface UserResponse {
  id?: number;
  username?: string;
  name?: string;
  phoneNumber?: string;
  role?: UserResponseRole;
  socialType?: UserResponseSocialType;
}

export interface PageResponseUserResponse {
  content?: UserResponse[];
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  sort?: string;
  last?: boolean;
}

export interface CommonResponsePageResponseUserResponse {
  isSuccess?: boolean;
  data?: PageResponseUserResponse;
}

export interface RefreshTokenResponse {
  userId?: number;
  refreshToken?: string;
  timeToLive?: number;
}

export interface CommonResponseListRefreshTokenResponse {
  isSuccess?: boolean;
  data?: RefreshTokenResponse[];
}

export type GetStoresParams = {
/**
 * 검색 키워드 (상점 이름)
 */
keyword?: string;
/**
 * 카테고리 필터
 */
category?: GetStoresCategory;
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type GetStoresCategory = typeof GetStoresCategory[keyof typeof GetStoresCategory];


export const GetStoresCategory = {
  BAR: 'BAR',
  CAFE: 'CAFE',
  RESTAURANT: 'RESTAURANT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BEAUTY_HEALTH: 'BEAUTY_HEALTH',
  ETC: 'ETC',
} as const;

export type CreateStoreBody = {
  /** 상품 이미지 목록 */
  images: string[];
  request: CreateStoreRequest;
};

export type GetReviewsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CreateReviewBody = {
  request: CreateReviewRequest;
  /** 리뷰 이미지 목록 */
  images?: string[];
};

export type GetStoreNewsListParams = {
/**
 * 페이징 정보 (page, size, sort)
 */
pageable: Pageable;
};

export type CreateStoreNewsBody = {
  /** 소식 이미지 목록 */
  images?: string[];
  request: CreateStoreNewsRequest;
};

export type CreateItemBody = {
  /** 상품 이미지 */
  image: string;
  request: CreateItemRequest;
};

export type GetCommentsParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type CompleteSocialSignupParams = {
userId: number;
request: CompleteSocialSignupRequest;
};

export type UploadExcelBody = {
  /** 업로드할 엑셀 파일 (.xlsx) */
  file: Blob;
};

export type UpdateStoreBody = {
  request: UpdateStoreRequest;
  images: string[];
};

export type UpdateStoreNewsBody = {
  /** 변경할 소식 이미지 목록 */
  images?: string[];
  request: UpdateStoreNewsRequest;
};

export type UpdateReviewBody = {
  request: UpdateReviewRequest;
  /** 리뷰 이미지 목록 */
  images?: string[];
};

export type UpdateItemBody = {
  /** 변경할 상품 이미지 */
  image: string;
  request: UpdateItemRequest;
};

export type HealthCheck200 = {[key: string]: { [key: string]: unknown }};

export type GetMyFavoritesParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

export type GetAllUsersParams = {
/**
 * 페이징 정보
 */
pageable: Pageable;
};

