/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemBody,
  UpdateItemBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 상점의 모든 상품을 조회합니다.
 * @summary [공통] 상점별 상품 목록 조회
 */
export type getItemsResponse200 = {
  data: Blob
  status: 200
}

export type getItemsResponse404 = {
  data: Blob
  status: 404
}
    
export type getItemsResponseSuccess = (getItemsResponse200) & {
  headers: Headers;
};
export type getItemsResponseError = (getItemsResponse404) & {
  headers: Headers;
};

export type getItemsResponse = (getItemsResponseSuccess | getItemsResponseError)

export const getGetItemsUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/items`
}

export const getItems = async (storeId: number, options?: RequestInit): Promise<getItemsResponse> => {
  
  return customFetch<getItemsResponse>(getGetItemsUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItemsQueryKey = (storeId?: number,) => {
    return [
    `/api/stores/${storeId}/items`
    ] as const;
    }

    
export const getGetItemsQueryOptions = <TData = Awaited<ReturnType<typeof getItems>>, TError = Blob>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItems>>> = ({ signal }) => getItems(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getItems>>>
export type GetItemsQueryError = Blob


export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = Blob>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItems>>,
          TError,
          Awaited<ReturnType<typeof getItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 상점별 상품 목록 조회
 */

export function useGetItems<TData = Awaited<ReturnType<typeof getItems>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItems>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점에 새로운 상품을 등록합니다. (본인 상점만 가능)
 * @summary [점주] 상품 등록
 */
export type createItemResponse201 = {
  data: Blob
  status: 201
}

export type createItemResponse400 = {
  data: Blob
  status: 400
}

export type createItemResponse403 = {
  data: Blob
  status: 403
}

export type createItemResponse404 = {
  data: Blob
  status: 404
}
    
export type createItemResponseSuccess = (createItemResponse201) & {
  headers: Headers;
};
export type createItemResponseError = (createItemResponse400 | createItemResponse403 | createItemResponse404) & {
  headers: Headers;
};

export type createItemResponse = (createItemResponseSuccess | createItemResponseError)

export const getCreateItemUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/items`
}

export const createItem = async (storeId: number,
    createItemBody: CreateItemBody, options?: RequestInit): Promise<createItemResponse> => {
    const formData = new FormData();
if(createItemBody.image !== undefined) {
 formData.append(`image`, createItemBody.image);
 }
if(createItemBody.request !== undefined) {
 formData.append(`request`, JSON.stringify(createItemBody.request));
 }

  return customFetch<createItemResponse>(getCreateItemUrl(storeId),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getCreateItemMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{storeId: number;data: CreateItemBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{storeId: number;data: CreateItemBody}, TContext> => {

const mutationKey = ['createItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItem>>, {storeId: number;data: CreateItemBody}> = (props) => {
          const {storeId,data} = props ?? {};

          return  createItem(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateItemMutationResult = NonNullable<Awaited<ReturnType<typeof createItem>>>
    export type CreateItemMutationBody = CreateItemBody
    export type CreateItemMutationError = Blob

    /**
 * @summary [점주] 상품 등록
 */
export const useCreateItem = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItem>>, TError,{storeId: number;data: CreateItemBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItem>>,
        TError,
        {storeId: number;data: CreateItemBody},
        TContext
      > => {
      return useMutation(getCreateItemMutationOptions(options), queryClient);
    }
    /**
 * 상품 ID로 상품의 상세 정보를 조회합니다.
 * @summary [공통] 상품 단건 조회
 */
export type getItemResponse200 = {
  data: Blob
  status: 200
}

export type getItemResponse404 = {
  data: Blob
  status: 404
}
    
export type getItemResponseSuccess = (getItemResponse200) & {
  headers: Headers;
};
export type getItemResponseError = (getItemResponse404) & {
  headers: Headers;
};

export type getItemResponse = (getItemResponseSuccess | getItemResponseError)

export const getGetItemUrl = (itemId: number,) => {


  

  return `/api/items/${itemId}`
}

export const getItem = async (itemId: number, options?: RequestInit): Promise<getItemResponse> => {
  
  return customFetch<getItemResponse>(getGetItemUrl(itemId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItemQueryKey = (itemId?: number,) => {
    return [
    `/api/items/${itemId}`
    ] as const;
    }

    
export const getGetItemQueryOptions = <TData = Awaited<ReturnType<typeof getItem>>, TError = Blob>(itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemQueryKey(itemId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItem>>> = ({ signal }) => getItem(itemId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(itemId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemQueryResult = NonNullable<Awaited<ReturnType<typeof getItem>>>
export type GetItemQueryError = Blob


export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = Blob>(
 itemId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = Blob>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItem>>,
          TError,
          Awaited<ReturnType<typeof getItem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = Blob>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 상품 단건 조회
 */

export function useGetItem<TData = Awaited<ReturnType<typeof getItem>>, TError = Blob>(
 itemId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemQueryOptions(itemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상품을 삭제합니다. (본인 상점만 가능)
 * @summary [점주] 상품 삭제
 */
export type deleteItemResponse204 = {
  data: Blob
  status: 204
}

export type deleteItemResponse403 = {
  data: Blob
  status: 403
}

export type deleteItemResponse404 = {
  data: Blob
  status: 404
}
    
export type deleteItemResponseSuccess = (deleteItemResponse204) & {
  headers: Headers;
};
export type deleteItemResponseError = (deleteItemResponse403 | deleteItemResponse404) & {
  headers: Headers;
};

export type deleteItemResponse = (deleteItemResponseSuccess | deleteItemResponseError)

export const getDeleteItemUrl = (itemId: number,) => {


  

  return `/api/items/${itemId}`
}

export const deleteItem = async (itemId: number, options?: RequestInit): Promise<deleteItemResponse> => {
  
  return customFetch<deleteItemResponse>(getDeleteItemUrl(itemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteItemMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext> => {

const mutationKey = ['deleteItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItem>>, {itemId: number}> = (props) => {
          const {itemId} = props ?? {};

          return  deleteItem(itemId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItem>>>
    
    export type DeleteItemMutationError = Blob

    /**
 * @summary [점주] 상품 삭제
 */
export const useDeleteItem = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItem>>, TError,{itemId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItem>>,
        TError,
        {itemId: number},
        TContext
      > => {
      return useMutation(getDeleteItemMutationOptions(options), queryClient);
    }
    /**
 * 상품 정보를 수정합니다. (본인 상점만 가능)
 * @summary [점주] 상품 수정
 */
export type updateItemResponse200 = {
  data: Blob
  status: 200
}

export type updateItemResponse403 = {
  data: Blob
  status: 403
}

export type updateItemResponse404 = {
  data: Blob
  status: 404
}
    
export type updateItemResponseSuccess = (updateItemResponse200) & {
  headers: Headers;
};
export type updateItemResponseError = (updateItemResponse403 | updateItemResponse404) & {
  headers: Headers;
};

export type updateItemResponse = (updateItemResponseSuccess | updateItemResponseError)

export const getUpdateItemUrl = (itemId: number,) => {


  

  return `/api/items/${itemId}`
}

export const updateItem = async (itemId: number,
    updateItemBody: UpdateItemBody, options?: RequestInit): Promise<updateItemResponse> => {
    const formData = new FormData();
if(updateItemBody.image !== undefined) {
 formData.append(`image`, updateItemBody.image);
 }
if(updateItemBody.request !== undefined) {
 formData.append(`request`, JSON.stringify(updateItemBody.request));
 }

  return customFetch<updateItemResponse>(getUpdateItemUrl(itemId),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
);}




export const getUpdateItemMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemBody}, TContext> => {

const mutationKey = ['updateItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItem>>, {itemId: number;data: UpdateItemBody}> = (props) => {
          const {itemId,data} = props ?? {};

          return  updateItem(itemId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateItem>>>
    export type UpdateItemMutationBody = UpdateItemBody
    export type UpdateItemMutationError = Blob

    /**
 * @summary [점주] 상품 수정
 */
export const useUpdateItem = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItem>>, TError,{itemId: number;data: UpdateItemBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItem>>,
        TError,
        {itemId: number;data: UpdateItemBody},
        TContext
      > => {
      return useMutation(getUpdateItemMutationOptions(options), queryClient);
    }
    