/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateItemCategoryBody,
  UpdateItemCategoryBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 매장의 상품 카테고리 목록을 조회합니다.
 * @summary [공통] 상품 카테고리 목록 조회
 */
export type getItemCategoriesResponse200 = {
  data: Blob
  status: 200
}
    
export type getItemCategoriesResponseSuccess = (getItemCategoriesResponse200) & {
  headers: Headers;
};
;

export type getItemCategoriesResponse = (getItemCategoriesResponseSuccess)

export const getGetItemCategoriesUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/item-categories`
}

export const getItemCategories = async (storeId: number, options?: RequestInit): Promise<getItemCategoriesResponse> => {
  
  return customFetch<getItemCategoriesResponse>(getGetItemCategoriesUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetItemCategoriesQueryKey = (storeId?: number,) => {
    return [
    `/api/stores/${storeId}/item-categories`
    ] as const;
    }

    
export const getGetItemCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getItemCategories>>, TError = unknown>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemCategoriesQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItemCategories>>> = ({ signal }) => getItemCategories(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getItemCategories>>>
export type GetItemCategoriesQueryError = unknown


export function useGetItemCategories<TData = Awaited<ReturnType<typeof getItemCategories>>, TError = unknown>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemCategories>>,
          TError,
          Awaited<ReturnType<typeof getItemCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemCategories<TData = Awaited<ReturnType<typeof getItemCategories>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemCategories>>,
          TError,
          Awaited<ReturnType<typeof getItemCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemCategories<TData = Awaited<ReturnType<typeof getItemCategories>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 상품 카테고리 목록 조회
 */

export function useGetItemCategories<TData = Awaited<ReturnType<typeof getItemCategories>>, TError = unknown>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemCategories>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemCategoriesQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 매장에 새로운 상품 카테고리를 등록합니다.
 * @summary [점주] 상품 카테고리 등록
 */
export type createItemCategoryResponse201 = {
  data: Blob
  status: 201
}

export type createItemCategoryResponse403 = {
  data: Blob
  status: 403
}

export type createItemCategoryResponse404 = {
  data: Blob
  status: 404
}
    
export type createItemCategoryResponseSuccess = (createItemCategoryResponse201) & {
  headers: Headers;
};
export type createItemCategoryResponseError = (createItemCategoryResponse403 | createItemCategoryResponse404) & {
  headers: Headers;
};

export type createItemCategoryResponse = (createItemCategoryResponseSuccess | createItemCategoryResponseError)

export const getCreateItemCategoryUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/item-categories`
}

export const createItemCategory = async (storeId: number,
    createItemCategoryBody: CreateItemCategoryBody, options?: RequestInit): Promise<createItemCategoryResponse> => {
  
  return customFetch<createItemCategoryResponse>(getCreateItemCategoryUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createItemCategoryBody,)
  }
);}




export const getCreateItemCategoryMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemCategory>>, TError,{storeId: number;data: CreateItemCategoryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createItemCategory>>, TError,{storeId: number;data: CreateItemCategoryBody}, TContext> => {

const mutationKey = ['createItemCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createItemCategory>>, {storeId: number;data: CreateItemCategoryBody}> = (props) => {
          const {storeId,data} = props ?? {};

          return  createItemCategory(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateItemCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createItemCategory>>>
    export type CreateItemCategoryMutationBody = CreateItemCategoryBody
    export type CreateItemCategoryMutationError = Blob

    /**
 * @summary [점주] 상품 카테고리 등록
 */
export const useCreateItemCategory = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createItemCategory>>, TError,{storeId: number;data: CreateItemCategoryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createItemCategory>>,
        TError,
        {storeId: number;data: CreateItemCategoryBody},
        TContext
      > => {
      return useMutation(getCreateItemCategoryMutationOptions(options), queryClient);
    }
    /**
 * 상품 카테고리를 삭제합니다. (사용 중인 상품이 있으면 삭제 불가)
 * @summary [점주] 상품 카테고리 삭제
 */
export type deleteItemCategoryResponse204 = {
  data: Blob
  status: 204
}

export type deleteItemCategoryResponse409 = {
  data: Blob
  status: 409
}
    
export type deleteItemCategoryResponseSuccess = (deleteItemCategoryResponse204) & {
  headers: Headers;
};
export type deleteItemCategoryResponseError = (deleteItemCategoryResponse409) & {
  headers: Headers;
};

export type deleteItemCategoryResponse = (deleteItemCategoryResponseSuccess | deleteItemCategoryResponseError)

export const getDeleteItemCategoryUrl = (storeId: number,
    categoryId: number,) => {


  

  return `/api/stores/${storeId}/item-categories/${categoryId}`
}

export const deleteItemCategory = async (storeId: number,
    categoryId: number, options?: RequestInit): Promise<deleteItemCategoryResponse> => {
  
  return customFetch<deleteItemCategoryResponse>(getDeleteItemCategoryUrl(storeId,categoryId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteItemCategoryMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItemCategory>>, TError,{storeId: number;categoryId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteItemCategory>>, TError,{storeId: number;categoryId: number}, TContext> => {

const mutationKey = ['deleteItemCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteItemCategory>>, {storeId: number;categoryId: number}> = (props) => {
          const {storeId,categoryId} = props ?? {};

          return  deleteItemCategory(storeId,categoryId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteItemCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteItemCategory>>>
    
    export type DeleteItemCategoryMutationError = Blob

    /**
 * @summary [점주] 상품 카테고리 삭제
 */
export const useDeleteItemCategory = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteItemCategory>>, TError,{storeId: number;categoryId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteItemCategory>>,
        TError,
        {storeId: number;categoryId: number},
        TContext
      > => {
      return useMutation(getDeleteItemCategoryMutationOptions(options), queryClient);
    }
    /**
 * 상품 카테고리 이름을 수정합니다.
 * @summary [점주] 상품 카테고리 수정
 */
export type updateItemCategoryResponse200 = {
  data: Blob
  status: 200
}
    
export type updateItemCategoryResponseSuccess = (updateItemCategoryResponse200) & {
  headers: Headers;
};
;

export type updateItemCategoryResponse = (updateItemCategoryResponseSuccess)

export const getUpdateItemCategoryUrl = (storeId: number,
    categoryId: number,) => {


  

  return `/api/stores/${storeId}/item-categories/${categoryId}`
}

export const updateItemCategory = async (storeId: number,
    categoryId: number,
    updateItemCategoryBody: UpdateItemCategoryBody, options?: RequestInit): Promise<updateItemCategoryResponse> => {
  
  return customFetch<updateItemCategoryResponse>(getUpdateItemCategoryUrl(storeId,categoryId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateItemCategoryBody,)
  }
);}




export const getUpdateItemCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItemCategory>>, TError,{storeId: number;categoryId: number;data: UpdateItemCategoryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateItemCategory>>, TError,{storeId: number;categoryId: number;data: UpdateItemCategoryBody}, TContext> => {

const mutationKey = ['updateItemCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateItemCategory>>, {storeId: number;categoryId: number;data: UpdateItemCategoryBody}> = (props) => {
          const {storeId,categoryId,data} = props ?? {};

          return  updateItemCategory(storeId,categoryId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateItemCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateItemCategory>>>
    export type UpdateItemCategoryMutationBody = UpdateItemCategoryBody
    export type UpdateItemCategoryMutationError = unknown

    /**
 * @summary [점주] 상품 카테고리 수정
 */
export const useUpdateItemCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateItemCategory>>, TError,{storeId: number;categoryId: number;data: UpdateItemCategoryBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateItemCategory>>,
        TError,
        {storeId: number;categoryId: number;data: UpdateItemCategoryBody},
        TContext
      > => {
      return useMutation(getUpdateItemCategoryMutationOptions(options), queryClient);
    }
    