/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangePasswordRequest,
  ChangeUsernameRequest,
  UpdateStudentProfileRequest,
  UpdateUniversityRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 학생의 대학, 단과대, 학과, 동아리 활동 여부를 조회합니다.
 * @summary [학생] 내 정보 조회
 */
export type getStudentInfoResponse200 = {
  data: Blob
  status: 200
}

export type getStudentInfoResponse403 = {
  data: Blob
  status: 403
}

export type getStudentInfoResponse404 = {
  data: Blob
  status: 404
}
    
export type getStudentInfoResponseSuccess = (getStudentInfoResponse200) & {
  headers: Headers;
};
export type getStudentInfoResponseError = (getStudentInfoResponse403 | getStudentInfoResponse404) & {
  headers: Headers;
};

export type getStudentInfoResponse = (getStudentInfoResponseSuccess | getStudentInfoResponseError)

export const getGetStudentInfoUrl = () => {


  

  return `/api/mypage/student/profile`
}

export const getStudentInfo = async ( options?: RequestInit): Promise<getStudentInfoResponse> => {
  
  return customFetch<getStudentInfoResponse>(getGetStudentInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStudentInfoQueryKey = () => {
    return [
    `/api/mypage/student/profile`
    ] as const;
    }

    
export const getGetStudentInfoQueryOptions = <TData = Awaited<ReturnType<typeof getStudentInfo>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentInfo>>> = ({ signal }) => getStudentInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentInfo>>>
export type GetStudentInfoQueryError = Blob


export function useGetStudentInfo<TData = Awaited<ReturnType<typeof getStudentInfo>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentInfo>>,
          TError,
          Awaited<ReturnType<typeof getStudentInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentInfo<TData = Awaited<ReturnType<typeof getStudentInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentInfo>>,
          TError,
          Awaited<ReturnType<typeof getStudentInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentInfo<TData = Awaited<ReturnType<typeof getStudentInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 내 정보 조회
 */

export function useGetStudentInfo<TData = Awaited<ReturnType<typeof getStudentInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 학생의 프로필(닉네임, 단과대, 학과, 동아리 가입여부)을 수정합니다. 대학 변경은 별도 API 사용.
 * @summary [학생] 프로필 수정
 */
export type updateStudentProfileResponse200 = {
  data: Blob
  status: 200
}

export type updateStudentProfileResponse400 = {
  data: Blob
  status: 400
}

export type updateStudentProfileResponse403 = {
  data: Blob
  status: 403
}
    
export type updateStudentProfileResponseSuccess = (updateStudentProfileResponse200) & {
  headers: Headers;
};
export type updateStudentProfileResponseError = (updateStudentProfileResponse400 | updateStudentProfileResponse403) & {
  headers: Headers;
};

export type updateStudentProfileResponse = (updateStudentProfileResponseSuccess | updateStudentProfileResponseError)

export const getUpdateStudentProfileUrl = () => {


  

  return `/api/mypage/student/profile`
}

export const updateStudentProfile = async (updateStudentProfileRequest: UpdateStudentProfileRequest, options?: RequestInit): Promise<updateStudentProfileResponse> => {
  
  return customFetch<updateStudentProfileResponse>(getUpdateStudentProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStudentProfileRequest,)
  }
);}




export const getUpdateStudentProfileMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudentProfile>>, TError,{data: UpdateStudentProfileRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStudentProfile>>, TError,{data: UpdateStudentProfileRequest}, TContext> => {

const mutationKey = ['updateStudentProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStudentProfile>>, {data: UpdateStudentProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateStudentProfile(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStudentProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateStudentProfile>>>
    export type UpdateStudentProfileMutationBody = UpdateStudentProfileRequest
    export type UpdateStudentProfileMutationError = Blob

    /**
 * @summary [학생] 프로필 수정
 */
export const useUpdateStudentProfile = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudentProfile>>, TError,{data: UpdateStudentProfileRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStudentProfile>>,
        TError,
        {data: UpdateStudentProfileRequest},
        TContext
      > => {
      return useMutation(getUpdateStudentProfileMutationOptions(options), queryClient);
    }
    /**
 * 학생의 소속 대학을 변경합니다. (기존 단과대/학과는 초기화됨)
 * @summary [학생] 대학 변경
 */
export type updateUniversityResponse200 = {
  data: Blob
  status: 200
}

export type updateUniversityResponse403 = {
  data: Blob
  status: 403
}

export type updateUniversityResponse404 = {
  data: Blob
  status: 404
}
    
export type updateUniversityResponseSuccess = (updateUniversityResponse200) & {
  headers: Headers;
};
export type updateUniversityResponseError = (updateUniversityResponse403 | updateUniversityResponse404) & {
  headers: Headers;
};

export type updateUniversityResponse = (updateUniversityResponseSuccess | updateUniversityResponseError)

export const getUpdateUniversityUrl = () => {


  

  return `/api/mypage/student/university`
}

export const updateUniversity = async (updateUniversityRequest: UpdateUniversityRequest, options?: RequestInit): Promise<updateUniversityResponse> => {
  
  return customFetch<updateUniversityResponse>(getUpdateUniversityUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUniversityRequest,)
  }
);}




export const getUpdateUniversityMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity>>, TError,{data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUniversity>>, TError,{data: UpdateUniversityRequest}, TContext> => {

const mutationKey = ['updateUniversity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUniversity>>, {data: UpdateUniversityRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateUniversity(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUniversityMutationResult = NonNullable<Awaited<ReturnType<typeof updateUniversity>>>
    export type UpdateUniversityMutationBody = UpdateUniversityRequest
    export type UpdateUniversityMutationError = Blob

    /**
 * @summary [학생] 대학 변경
 */
export const useUpdateUniversity = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUniversity>>, TError,{data: UpdateUniversityRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUniversity>>,
        TError,
        {data: UpdateUniversityRequest},
        TContext
      > => {
      return useMutation(getUpdateUniversityMutationOptions(options), queryClient);
    }
    /**
 * 사용자의 아이디를 변경합니다.
 * @summary [공통] 아이디 변경
 */
export type changeUsernameResponse200 = {
  data: Blob
  status: 200
}

export type changeUsernameResponse400 = {
  data: Blob
  status: 400
}

export type changeUsernameResponse409 = {
  data: Blob
  status: 409
}
    
export type changeUsernameResponseSuccess = (changeUsernameResponse200) & {
  headers: Headers;
};
export type changeUsernameResponseError = (changeUsernameResponse400 | changeUsernameResponse409) & {
  headers: Headers;
};

export type changeUsernameResponse = (changeUsernameResponseSuccess | changeUsernameResponseError)

export const getChangeUsernameUrl = () => {


  

  return `/api/mypage/change-username`
}

export const changeUsername = async (changeUsernameRequest: ChangeUsernameRequest, options?: RequestInit): Promise<changeUsernameResponse> => {
  
  return customFetch<changeUsernameResponse>(getChangeUsernameUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changeUsernameRequest,)
  }
);}




export const getChangeUsernameMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUsername>>, TError,{data: ChangeUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeUsername>>, TError,{data: ChangeUsernameRequest}, TContext> => {

const mutationKey = ['changeUsername'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeUsername>>, {data: ChangeUsernameRequest}> = (props) => {
          const {data} = props ?? {};

          return  changeUsername(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof changeUsername>>>
    export type ChangeUsernameMutationBody = ChangeUsernameRequest
    export type ChangeUsernameMutationError = Blob

    /**
 * @summary [공통] 아이디 변경
 */
export const useChangeUsername = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeUsername>>, TError,{data: ChangeUsernameRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeUsername>>,
        TError,
        {data: ChangeUsernameRequest},
        TContext
      > => {
      return useMutation(getChangeUsernameMutationOptions(options), queryClient);
    }
    /**
 * 사용자의 비밀번호를 변경합니다.
 * @summary [공통] 비밀번호 변경
 */
export type changePasswordResponse200 = {
  data: Blob
  status: 200
}

export type changePasswordResponse400 = {
  data: Blob
  status: 400
}
    
export type changePasswordResponseSuccess = (changePasswordResponse200) & {
  headers: Headers;
};
export type changePasswordResponseError = (changePasswordResponse400) & {
  headers: Headers;
};

export type changePasswordResponse = (changePasswordResponseSuccess | changePasswordResponseError)

export const getChangePasswordUrl = () => {


  

  return `/api/mypage/change-password`
}

export const changePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<changePasswordResponse> => {
  
  return customFetch<changePasswordResponse>(getChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordRequest,)
  }
);}




export const getChangePasswordMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: ChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePasswordRequest
    export type ChangePasswordMutationError = Blob

    /**
 * @summary [공통] 비밀번호 변경
 */
export const useChangePassword = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: ChangePasswordRequest},
        TContext
      > => {
      return useMutation(getChangePasswordMutationOptions(options), queryClient);
    }
    /**
 * 점주의 이름, 이메일, 아이디, 성별, 생년월일을 조회합니다.
 * @summary [점주] 내 정보 조회
 */
export type getOwnerInfoResponse200 = {
  data: Blob
  status: 200
}

export type getOwnerInfoResponse403 = {
  data: Blob
  status: 403
}

export type getOwnerInfoResponse404 = {
  data: Blob
  status: 404
}
    
export type getOwnerInfoResponseSuccess = (getOwnerInfoResponse200) & {
  headers: Headers;
};
export type getOwnerInfoResponseError = (getOwnerInfoResponse403 | getOwnerInfoResponse404) & {
  headers: Headers;
};

export type getOwnerInfoResponse = (getOwnerInfoResponseSuccess | getOwnerInfoResponseError)

export const getGetOwnerInfoUrl = () => {


  

  return `/api/mypage/owner/profile`
}

export const getOwnerInfo = async ( options?: RequestInit): Promise<getOwnerInfoResponse> => {
  
  return customFetch<getOwnerInfoResponse>(getGetOwnerInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOwnerInfoQueryKey = () => {
    return [
    `/api/mypage/owner/profile`
    ] as const;
    }

    
export const getGetOwnerInfoQueryOptions = <TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOwnerInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOwnerInfo>>> = ({ signal }) => getOwnerInfo({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getOwnerInfo>>>
export type GetOwnerInfoQueryError = Blob


export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnerInfo>>,
          TError,
          Awaited<ReturnType<typeof getOwnerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnerInfo>>,
          TError,
          Awaited<ReturnType<typeof getOwnerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 내 정보 조회
 */

export function useGetOwnerInfo<TData = Awaited<ReturnType<typeof getOwnerInfo>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOwnerInfo>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOwnerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




