/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOrganizationRequest,
  UpdateOrganizationRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 대학의 모든 소속을 조회합니다.
 * @summary [공통] 특정 대학의 소속 목록 조회
 */
export type getOrganizationsResponse200 = {
  data: Blob
  status: 200
}
    
export type getOrganizationsResponseSuccess = (getOrganizationsResponse200) & {
  headers: Headers;
};
;

export type getOrganizationsResponse = (getOrganizationsResponseSuccess)

export const getGetOrganizationsUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}/organizations`
}

export const getOrganizations = async (universityId: number, options?: RequestInit): Promise<getOrganizationsResponse> => {
  
  return customFetch<getOrganizationsResponse>(getGetOrganizationsUrl(universityId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetOrganizationsQueryKey = (universityId: number,) => {
    return [
    `/api/universities/${universityId}/organizations`
    ] as const;
    }

    
export const getGetOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizations>>, TError = unknown>(universityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsQueryKey(universityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizations>>> = ({ signal }) => getOrganizations(universityId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(universityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizations>>>
export type GetOrganizationsQueryError = unknown


export function useGetOrganizations<TData = Awaited<ReturnType<typeof getOrganizations>>, TError = unknown>(
 universityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getOrganizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizations<TData = Awaited<ReturnType<typeof getOrganizations>>, TError = unknown>(
 universityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getOrganizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizations<TData = Awaited<ReturnType<typeof getOrganizations>>, TError = unknown>(
 universityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 특정 대학의 소속 목록 조회
 */

export function useGetOrganizations<TData = Awaited<ReturnType<typeof getOrganizations>>, TError = unknown>(
 universityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationsQueryOptions(universityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 대학에 새로운 소속(단과대, 학과 등)을 등록합니다.
 * @summary [학생회] 특정 대학에 소속 등록
 */
export type createOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type createOrganizationResponseSuccess = (createOrganizationResponse200) & {
  headers: Headers;
};
;

export type createOrganizationResponse = (createOrganizationResponseSuccess)

export const getCreateOrganizationUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}/organizations`
}

export const createOrganization = async (universityId: number,
    createOrganizationRequest: CreateOrganizationRequest, options?: RequestInit): Promise<createOrganizationResponse> => {
  
  return customFetch<createOrganizationResponse>(getCreateOrganizationUrl(universityId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationRequest,)
  }
);}




export const getCreateOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{universityId: number;data: CreateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{universityId: number;data: CreateOrganizationRequest}, TContext> => {

const mutationKey = ['createOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganization>>, {universityId: number;data: CreateOrganizationRequest}> = (props) => {
          const {universityId,data} = props ?? {};

          return  createOrganization(universityId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganization>>>
    export type CreateOrganizationMutationBody = CreateOrganizationRequest
    export type CreateOrganizationMutationError = unknown

    /**
 * @summary [학생회] 특정 대학에 소속 등록
 */
export const useCreateOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{universityId: number;data: CreateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrganization>>,
        TError,
        {universityId: number;data: CreateOrganizationRequest},
        TContext
      > => {
      return useMutation(getCreateOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 학생이 특정 소속에 가입합니다.
 * @summary [학생] 소속 가입
 */
export type joinOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type joinOrganizationResponseSuccess = (joinOrganizationResponse200) & {
  headers: Headers;
};
;

export type joinOrganizationResponse = (joinOrganizationResponseSuccess)

export const getJoinOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}/membership`
}

export const joinOrganization = async (organizationId: number, options?: RequestInit): Promise<joinOrganizationResponse> => {
  
  return customFetch<joinOrganizationResponse>(getJoinOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getJoinOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['joinOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof joinOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  joinOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type JoinOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof joinOrganization>>>
    
    export type JoinOrganizationMutationError = unknown

    /**
 * @summary [학생] 소속 가입
 */
export const useJoinOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof joinOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof joinOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getJoinOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 학생이 특정 소속에서 탈퇴합니다.
 * @summary [학생] 소속 탈퇴
 */
export type leaveOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type leaveOrganizationResponseSuccess = (leaveOrganizationResponse200) & {
  headers: Headers;
};
;

export type leaveOrganizationResponse = (leaveOrganizationResponseSuccess)

export const getLeaveOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}/membership`
}

export const leaveOrganization = async (organizationId: number, options?: RequestInit): Promise<leaveOrganizationResponse> => {
  
  return customFetch<leaveOrganizationResponse>(getLeaveOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getLeaveOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['leaveOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  leaveOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LeaveOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof leaveOrganization>>>
    
    export type LeaveOrganizationMutationError = unknown

    /**
 * @summary [학생] 소속 탈퇴
 */
export const useLeaveOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof leaveOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getLeaveOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 학생이 소속을 변경합니다. (기존 동종 소속 자동 탈퇴)
 * @summary [학생] 소속 변경
 */
export type changeOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type changeOrganizationResponseSuccess = (changeOrganizationResponse200) & {
  headers: Headers;
};
;

export type changeOrganizationResponse = (changeOrganizationResponseSuccess)

export const getChangeOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}/membership`
}

export const changeOrganization = async (organizationId: number, options?: RequestInit): Promise<changeOrganizationResponse> => {
  
  return customFetch<changeOrganizationResponse>(getChangeOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}




export const getChangeOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['changeOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  changeOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangeOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof changeOrganization>>>
    
    export type ChangeOrganizationMutationError = unknown

    /**
 * @summary [학생] 소속 변경
 */
export const useChangeOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getChangeOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 소속을 삭제합니다.
 * @summary [학생회] 소속 삭제
 */
export type deleteOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type deleteOrganizationResponseSuccess = (deleteOrganizationResponse200) & {
  headers: Headers;
};
;

export type deleteOrganizationResponse = (deleteOrganizationResponseSuccess)

export const getDeleteOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}`
}

export const deleteOrganization = async (organizationId: number, options?: RequestInit): Promise<deleteOrganizationResponse> => {
  
  return customFetch<deleteOrganizationResponse>(getDeleteOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['deleteOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganization>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  deleteOrganization(organizationId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganization>>>
    
    export type DeleteOrganizationMutationError = unknown

    /**
 * @summary [학생회] 소속 삭제
 */
export const useDeleteOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrganization>>,
        TError,
        {organizationId: number},
        TContext
      > => {
      return useMutation(getDeleteOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 소속 정보를 수정합니다.
 * @summary [학생회] 소속 수정
 */
export type updateOrganizationResponse200 = {
  data: Blob
  status: 200
}
    
export type updateOrganizationResponseSuccess = (updateOrganizationResponse200) & {
  headers: Headers;
};
;

export type updateOrganizationResponse = (updateOrganizationResponseSuccess)

export const getUpdateOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}`
}

export const updateOrganization = async (organizationId: number,
    updateOrganizationRequest: UpdateOrganizationRequest, options?: RequestInit): Promise<updateOrganizationResponse> => {
  
  return customFetch<updateOrganizationResponse>(getUpdateOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrganizationRequest,)
  }
);}




export const getUpdateOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{organizationId: number;data: UpdateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{organizationId: number;data: UpdateOrganizationRequest}, TContext> => {

const mutationKey = ['updateOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganization>>, {organizationId: number;data: UpdateOrganizationRequest}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  updateOrganization(organizationId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganization>>>
    export type UpdateOrganizationMutationBody = UpdateOrganizationRequest
    export type UpdateOrganizationMutationError = unknown

    /**
 * @summary [학생회] 소속 수정
 */
export const useUpdateOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{organizationId: number;data: UpdateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganization>>,
        TError,
        {organizationId: number;data: UpdateOrganizationRequest},
        TContext
      > => {
      return useMutation(getUpdateOrganizationMutationOptions(options), queryClient);
    }
    /**
 * 단과대학에 속한 학과 목록을 조회합니다.
 * @summary [공통] 특정 단과대학의 학과 목록 조회
 */
export type getDepartmentsByCollegeResponse200 = {
  data: Blob
  status: 200
}
    
export type getDepartmentsByCollegeResponseSuccess = (getDepartmentsByCollegeResponse200) & {
  headers: Headers;
};
;

export type getDepartmentsByCollegeResponse = (getDepartmentsByCollegeResponseSuccess)

export const getGetDepartmentsByCollegeUrl = (collegeId: number,) => {


  

  return `/api/organizations/${collegeId}/departments`
}

export const getDepartmentsByCollege = async (collegeId: number, options?: RequestInit): Promise<getDepartmentsByCollegeResponse> => {
  
  return customFetch<getDepartmentsByCollegeResponse>(getGetDepartmentsByCollegeUrl(collegeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDepartmentsByCollegeQueryKey = (collegeId: number,) => {
    return [
    `/api/organizations/${collegeId}/departments`
    ] as const;
    }

    
export const getGetDepartmentsByCollegeQueryOptions = <TData = Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError = unknown>(collegeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDepartmentsByCollegeQueryKey(collegeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartmentsByCollege>>> = ({ signal }) => getDepartmentsByCollege(collegeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(collegeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsByCollegeQueryResult = NonNullable<Awaited<ReturnType<typeof getDepartmentsByCollege>>>
export type GetDepartmentsByCollegeQueryError = unknown


export function useGetDepartmentsByCollege<TData = Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError = unknown>(
 collegeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentsByCollege>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentsByCollege>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartmentsByCollege<TData = Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError = unknown>(
 collegeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDepartmentsByCollege>>,
          TError,
          Awaited<ReturnType<typeof getDepartmentsByCollege>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartmentsByCollege<TData = Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError = unknown>(
 collegeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [공통] 특정 단과대학의 학과 목록 조회
 */

export function useGetDepartmentsByCollege<TData = Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError = unknown>(
 collegeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartmentsByCollege>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDepartmentsByCollegeQueryOptions(collegeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




