/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseListOrganizationResponse,
  CommonResponseLong,
  CommonResponseVoid,
  CreateOrganizationRequest,
  UpdateOrganizationRequest
} from './generated.schemas';



/**
 * 대학의 모든 소속을 조회합니다.
 * @summary [공통] 특정 대학의 소속 목록 조회
 */
export type getOrganizationsResponse200 = {
  data: CommonResponseListOrganizationResponse
  status: 200
}
    
export type getOrganizationsResponseSuccess = (getOrganizationsResponse200) & {
  headers: Headers;
};
;

export type getOrganizationsResponse = (getOrganizationsResponseSuccess)

export const getGetOrganizationsUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}/organizations`
}

export const getOrganizations = async (universityId: number, options?: RequestInit): Promise<getOrganizationsResponse> => {
  
  const res = await fetch(getGetOrganizationsUrl(universityId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOrganizationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOrganizationsResponse
}


/**
 * 대학에 새로운 소속(단과대, 학과 등)을 등록합니다.
 * @summary [관리자] 특정 대학에 소속 등록
 */
export type createOrganizationResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type createOrganizationResponseSuccess = (createOrganizationResponse200) & {
  headers: Headers;
};
;

export type createOrganizationResponse = (createOrganizationResponseSuccess)

export const getCreateOrganizationUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}/organizations`
}

export const createOrganization = async (universityId: number,
    createOrganizationRequest: CreateOrganizationRequest, options?: RequestInit): Promise<createOrganizationResponse> => {
  
  const res = await fetch(getCreateOrganizationUrl(universityId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOrganizationResponse
}


/**
 * 학생이 특정 소속에 가입합니다.
 * @summary [학생] 소속 가입
 */
export type joinOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type joinOrganizationResponseSuccess = (joinOrganizationResponse200) & {
  headers: Headers;
};
;

export type joinOrganizationResponse = (joinOrganizationResponseSuccess)

export const getJoinOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}/membership`
}

export const joinOrganization = async (organizationId: number, options?: RequestInit): Promise<joinOrganizationResponse> => {
  
  const res = await fetch(getJoinOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: joinOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as joinOrganizationResponse
}


/**
 * 학생이 특정 소속에서 탈퇴합니다.
 * @summary [학생] 소속 탈퇴
 */
export type leaveOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type leaveOrganizationResponseSuccess = (leaveOrganizationResponse200) & {
  headers: Headers;
};
;

export type leaveOrganizationResponse = (leaveOrganizationResponseSuccess)

export const getLeaveOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}/membership`
}

export const leaveOrganization = async (organizationId: number, options?: RequestInit): Promise<leaveOrganizationResponse> => {
  
  const res = await fetch(getLeaveOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: leaveOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as leaveOrganizationResponse
}


/**
 * 소속을 삭제합니다.
 * @summary [관리자] 소속 삭제
 */
export type deleteOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteOrganizationResponseSuccess = (deleteOrganizationResponse200) & {
  headers: Headers;
};
;

export type deleteOrganizationResponse = (deleteOrganizationResponseSuccess)

export const getDeleteOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}`
}

export const deleteOrganization = async (organizationId: number, options?: RequestInit): Promise<deleteOrganizationResponse> => {
  
  const res = await fetch(getDeleteOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteOrganizationResponse
}


/**
 * 소속 정보를 수정합니다.
 * @summary [관리자] 소속 수정
 */
export type updateOrganizationResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type updateOrganizationResponseSuccess = (updateOrganizationResponse200) & {
  headers: Headers;
};
;

export type updateOrganizationResponse = (updateOrganizationResponseSuccess)

export const getUpdateOrganizationUrl = (organizationId: number,) => {


  

  return `/api/organizations/${organizationId}`
}

export const updateOrganization = async (organizationId: number,
    updateOrganizationRequest: UpdateOrganizationRequest, options?: RequestInit): Promise<updateOrganizationResponse> => {
  
  const res = await fetch(getUpdateOrganizationUrl(organizationId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateOrganizationRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOrganizationResponse
}


