/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseLong,
  CommonResponseVoid,
  CreatePartnershipRequest,
  SwaggerErrorResponse,
  UpdatePartnershipRequest
} from './generated.schemas';



/**
 * 특정 조직에 제휴를 등록합니다.
 * @summary [점주] 제휴 등록
 */
export type createPartnershipResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createPartnershipResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createPartnershipResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createPartnershipResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type createPartnershipResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type createPartnershipResponseSuccess = (createPartnershipResponse201) & {
  headers: Headers;
};
export type createPartnershipResponseError = (createPartnershipResponse400 | createPartnershipResponse403 | createPartnershipResponse404 | createPartnershipResponse409) & {
  headers: Headers;
};

export type createPartnershipResponse = (createPartnershipResponseSuccess | createPartnershipResponseError)

export const getCreatePartnershipUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/partnerships`
}

export const createPartnership = async (storeId: number,
    createPartnershipRequest: CreatePartnershipRequest, options?: RequestInit): Promise<createPartnershipResponse> => {
  
  const res = await fetch(getCreatePartnershipUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPartnershipRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPartnershipResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPartnershipResponse
}


/**
 * 제휴를 삭제합니다.
 * @summary [점주] 제휴 삭제
 */
export type deletePartnershipResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deletePartnershipResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deletePartnershipResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deletePartnershipResponseSuccess = (deletePartnershipResponse204) & {
  headers: Headers;
};
export type deletePartnershipResponseError = (deletePartnershipResponse403 | deletePartnershipResponse404) & {
  headers: Headers;
};

export type deletePartnershipResponse = (deletePartnershipResponseSuccess | deletePartnershipResponseError)

export const getDeletePartnershipUrl = (storeId: number,
    partnershipId: number,) => {


  

  return `/api/stores/${storeId}/partnerships/${partnershipId}`
}

export const deletePartnership = async (storeId: number,
    partnershipId: number, options?: RequestInit): Promise<deletePartnershipResponse> => {
  
  const res = await fetch(getDeletePartnershipUrl(storeId,partnershipId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deletePartnershipResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deletePartnershipResponse
}


/**
 * 제휴 내용을 수정합니다.
 * @summary [점주] 제휴 혜택 수정
 */
export type updatePartnershipBenefitResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updatePartnershipBenefitResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updatePartnershipBenefitResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updatePartnershipBenefitResponseSuccess = (updatePartnershipBenefitResponse200) & {
  headers: Headers;
};
export type updatePartnershipBenefitResponseError = (updatePartnershipBenefitResponse403 | updatePartnershipBenefitResponse404) & {
  headers: Headers;
};

export type updatePartnershipBenefitResponse = (updatePartnershipBenefitResponseSuccess | updatePartnershipBenefitResponseError)

export const getUpdatePartnershipBenefitUrl = (storeId: number,
    partnershipId: number,) => {


  

  return `/api/stores/${storeId}/partnerships/${partnershipId}`
}

export const updatePartnershipBenefit = async (storeId: number,
    partnershipId: number,
    updatePartnershipRequest: UpdatePartnershipRequest, options?: RequestInit): Promise<updatePartnershipBenefitResponse> => {
  
  const res = await fetch(getUpdatePartnershipBenefitUrl(storeId,partnershipId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePartnershipRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updatePartnershipBenefitResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updatePartnershipBenefitResponse
}


