/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CommonResponseLong,
  CommonResponseVoid,
  CreatePartnershipRequest,
  SwaggerErrorResponse,
  UpdatePartnershipRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 조직에 제휴를 등록합니다.
 * @summary [점주] 제휴 등록
 */
export type createPartnershipResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createPartnershipResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createPartnershipResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createPartnershipResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type createPartnershipResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type createPartnershipResponseSuccess = (createPartnershipResponse201) & {
  headers: Headers;
};
export type createPartnershipResponseError = (createPartnershipResponse400 | createPartnershipResponse403 | createPartnershipResponse404 | createPartnershipResponse409) & {
  headers: Headers;
};

export type createPartnershipResponse = (createPartnershipResponseSuccess | createPartnershipResponseError)

export const getCreatePartnershipUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/partnerships`
}

export const createPartnership = async (storeId: number,
    createPartnershipRequest: CreatePartnershipRequest, options?: RequestInit): Promise<createPartnershipResponse> => {
  
  return customFetch<createPartnershipResponse>(getCreatePartnershipUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPartnershipRequest,)
  }
);}




export const getCreatePartnershipMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPartnership>>, TError,{storeId: number;data: CreatePartnershipRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPartnership>>, TError,{storeId: number;data: CreatePartnershipRequest}, TContext> => {

const mutationKey = ['createPartnership'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPartnership>>, {storeId: number;data: CreatePartnershipRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  createPartnership(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePartnershipMutationResult = NonNullable<Awaited<ReturnType<typeof createPartnership>>>
    export type CreatePartnershipMutationBody = CreatePartnershipRequest
    export type CreatePartnershipMutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 제휴 등록
 */
export const useCreatePartnership = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPartnership>>, TError,{storeId: number;data: CreatePartnershipRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPartnership>>,
        TError,
        {storeId: number;data: CreatePartnershipRequest},
        TContext
      > => {
      return useMutation(getCreatePartnershipMutationOptions(options), queryClient);
    }
    /**
 * 제휴를 삭제합니다.
 * @summary [점주] 제휴 삭제
 */
export type deletePartnershipResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deletePartnershipResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deletePartnershipResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deletePartnershipResponseSuccess = (deletePartnershipResponse204) & {
  headers: Headers;
};
export type deletePartnershipResponseError = (deletePartnershipResponse403 | deletePartnershipResponse404) & {
  headers: Headers;
};

export type deletePartnershipResponse = (deletePartnershipResponseSuccess | deletePartnershipResponseError)

export const getDeletePartnershipUrl = (storeId: number,
    partnershipId: number,) => {


  

  return `/api/stores/${storeId}/partnerships/${partnershipId}`
}

export const deletePartnership = async (storeId: number,
    partnershipId: number, options?: RequestInit): Promise<deletePartnershipResponse> => {
  
  return customFetch<deletePartnershipResponse>(getDeletePartnershipUrl(storeId,partnershipId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePartnershipMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePartnership>>, TError,{storeId: number;partnershipId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePartnership>>, TError,{storeId: number;partnershipId: number}, TContext> => {

const mutationKey = ['deletePartnership'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePartnership>>, {storeId: number;partnershipId: number}> = (props) => {
          const {storeId,partnershipId} = props ?? {};

          return  deletePartnership(storeId,partnershipId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePartnershipMutationResult = NonNullable<Awaited<ReturnType<typeof deletePartnership>>>
    
    export type DeletePartnershipMutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 제휴 삭제
 */
export const useDeletePartnership = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePartnership>>, TError,{storeId: number;partnershipId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePartnership>>,
        TError,
        {storeId: number;partnershipId: number},
        TContext
      > => {
      return useMutation(getDeletePartnershipMutationOptions(options), queryClient);
    }
    /**
 * 제휴 내용을 수정합니다.
 * @summary [점주] 제휴 혜택 수정
 */
export type updatePartnershipBenefitResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updatePartnershipBenefitResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updatePartnershipBenefitResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updatePartnershipBenefitResponseSuccess = (updatePartnershipBenefitResponse200) & {
  headers: Headers;
};
export type updatePartnershipBenefitResponseError = (updatePartnershipBenefitResponse403 | updatePartnershipBenefitResponse404) & {
  headers: Headers;
};

export type updatePartnershipBenefitResponse = (updatePartnershipBenefitResponseSuccess | updatePartnershipBenefitResponseError)

export const getUpdatePartnershipBenefitUrl = (storeId: number,
    partnershipId: number,) => {


  

  return `/api/stores/${storeId}/partnerships/${partnershipId}`
}

export const updatePartnershipBenefit = async (storeId: number,
    partnershipId: number,
    updatePartnershipRequest: UpdatePartnershipRequest, options?: RequestInit): Promise<updatePartnershipBenefitResponse> => {
  
  return customFetch<updatePartnershipBenefitResponse>(getUpdatePartnershipBenefitUrl(storeId,partnershipId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePartnershipRequest,)
  }
);}




export const getUpdatePartnershipBenefitMutationOptions = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePartnershipBenefit>>, TError,{storeId: number;partnershipId: number;data: UpdatePartnershipRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePartnershipBenefit>>, TError,{storeId: number;partnershipId: number;data: UpdatePartnershipRequest}, TContext> => {

const mutationKey = ['updatePartnershipBenefit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePartnershipBenefit>>, {storeId: number;partnershipId: number;data: UpdatePartnershipRequest}> = (props) => {
          const {storeId,partnershipId,data} = props ?? {};

          return  updatePartnershipBenefit(storeId,partnershipId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePartnershipBenefitMutationResult = NonNullable<Awaited<ReturnType<typeof updatePartnershipBenefit>>>
    export type UpdatePartnershipBenefitMutationBody = UpdatePartnershipRequest
    export type UpdatePartnershipBenefitMutationError = SwaggerErrorResponse

    /**
 * @summary [점주] 제휴 혜택 수정
 */
export const useUpdatePartnershipBenefit = <TError = SwaggerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePartnershipBenefit>>, TError,{storeId: number;partnershipId: number;data: UpdatePartnershipRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePartnershipBenefit>>,
        TError,
        {storeId: number;partnershipId: number;data: UpdatePartnershipRequest},
        TContext
      > => {
      return useMutation(getUpdatePartnershipBenefitMutationOptions(options), queryClient);
    }
    