/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseLong,
  CommonResponsePageResponseReviewResponse,
  CommonResponseReviewStatsResponse,
  CommonResponseVoid,
  CreateReviewBody,
  GetReviewsParams,
  ReportRequest,
  SwaggerErrorResponse,
  UpdateReviewBody
} from './generated.schemas';



/**
 * 특정 상점의 리뷰 목록을 페이징하여 조회합니다.
 * @summary [공통] 상점 리뷰 목록 조회
 */
export type getReviewsResponse200 = {
  data: CommonResponsePageResponseReviewResponse
  status: 200
}

export type getReviewsResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getReviewsResponseSuccess = (getReviewsResponse200) & {
  headers: Headers;
};
export type getReviewsResponseError = (getReviewsResponse404) & {
  headers: Headers;
};

export type getReviewsResponse = (getReviewsResponseSuccess | getReviewsResponseError)

export const getGetReviewsUrl = (storeId: number,
    params: GetReviewsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/stores/${storeId}/reviews?${stringifiedParams}` : `/api/stores/${storeId}/reviews`
}

export const getReviews = async (storeId: number,
    params: GetReviewsParams, options?: RequestInit): Promise<getReviewsResponse> => {
  
  const res = await fetch(getGetReviewsUrl(storeId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getReviewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReviewsResponse
}


/**
 * 상점에 대한 리뷰를 작성합니다.
 * @summary [학생] 리뷰 작성
 */
export type createReviewResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createReviewResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createReviewResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type createReviewResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type createReviewResponseSuccess = (createReviewResponse201) & {
  headers: Headers;
};
export type createReviewResponseError = (createReviewResponse400 | createReviewResponse404 | createReviewResponse409) & {
  headers: Headers;
};

export type createReviewResponse = (createReviewResponseSuccess | createReviewResponseError)

export const getCreateReviewUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/reviews`
}

export const createReview = async (storeId: number,
    createReviewBody: CreateReviewBody, options?: RequestInit): Promise<createReviewResponse> => {
  
  const res = await fetch(getCreateReviewUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createReviewBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createReviewResponse
}


/**
 * 특정 리뷰를 신고합니다.
 * @summary [공통] 리뷰 신고 
 */
export type reportReviewResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type reportReviewResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type reportReviewResponseSuccess = (reportReviewResponse200) & {
  headers: Headers;
};
export type reportReviewResponseError = (reportReviewResponse404) & {
  headers: Headers;
};

export type reportReviewResponse = (reportReviewResponseSuccess | reportReviewResponseError)

export const getReportReviewUrl = (reviewId: number,) => {


  

  return `/api/reviews/${reviewId}/reports`
}

export const reportReview = async (reviewId: number,
    reportRequest: ReportRequest, options?: RequestInit): Promise<reportReviewResponse> => {
  
  const res = await fetch(getReportReviewUrl(reviewId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: reportReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as reportReviewResponse
}


/**
 * 리뷰에 좋아요를 누릅니다.
 * @summary [공통] 리뷰 좋아요
 */
export type addLikeResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type addLikeResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type addLikeResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type addLikeResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type addLikeResponseSuccess = (addLikeResponse200) & {
  headers: Headers;
};
export type addLikeResponseError = (addLikeResponse400 | addLikeResponse404 | addLikeResponse409) & {
  headers: Headers;
};

export type addLikeResponse = (addLikeResponseSuccess | addLikeResponseError)

export const getAddLikeUrl = (reviewId: number,) => {


  

  return `/api/reviews/${reviewId}/likes`
}

export const addLike = async (reviewId: number, options?: RequestInit): Promise<addLikeResponse> => {
  
  const res = await fetch(getAddLikeUrl(reviewId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addLikeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addLikeResponse
}


/**
 * 리뷰 좋아요를 취소합니다.
 * @summary [공통] 리뷰 좋아요 취소
 */
export type removeLikeResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type removeLikeResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type removeLikeResponseSuccess = (removeLikeResponse200) & {
  headers: Headers;
};
export type removeLikeResponseError = (removeLikeResponse404) & {
  headers: Headers;
};

export type removeLikeResponse = (removeLikeResponseSuccess | removeLikeResponseError)

export const getRemoveLikeUrl = (reviewId: number,) => {


  

  return `/api/reviews/${reviewId}/likes`
}

export const removeLike = async (reviewId: number, options?: RequestInit): Promise<removeLikeResponse> => {
  
  const res = await fetch(getRemoveLikeUrl(reviewId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: removeLikeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeLikeResponse
}


/**
 * 작성한 리뷰를 삭제합니다. (본인만 가능)
 * @summary [학생] 리뷰 삭제
 */
export type deleteReviewResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteReviewResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteReviewResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteReviewResponseSuccess = (deleteReviewResponse204) & {
  headers: Headers;
};
export type deleteReviewResponseError = (deleteReviewResponse403 | deleteReviewResponse404) & {
  headers: Headers;
};

export type deleteReviewResponse = (deleteReviewResponseSuccess | deleteReviewResponseError)

export const getDeleteReviewUrl = (reviewId: number,) => {


  

  return `/api/reviews/${reviewId}`
}

export const deleteReview = async (reviewId: number, options?: RequestInit): Promise<deleteReviewResponse> => {
  
  const res = await fetch(getDeleteReviewUrl(reviewId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteReviewResponse
}


/**
 * 작성한 리뷰를 수정합니다. (본인만 가능)
 * @summary [학생] 리뷰 수정
 */
export type updateReviewResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateReviewResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateReviewResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type updateReviewResponseSuccess = (updateReviewResponse200) & {
  headers: Headers;
};
export type updateReviewResponseError = (updateReviewResponse403 | updateReviewResponse404) & {
  headers: Headers;
};

export type updateReviewResponse = (updateReviewResponseSuccess | updateReviewResponseError)

export const getUpdateReviewUrl = (reviewId: number,) => {


  

  return `/api/reviews/${reviewId}`
}

export const updateReview = async (reviewId: number,
    updateReviewBody: UpdateReviewBody, options?: RequestInit): Promise<updateReviewResponse> => {
  
  const res = await fetch(getUpdateReviewUrl(reviewId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateReviewBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateReviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateReviewResponse
}


/**
 * 상점의 평점 평균, 총 리뷰 수, 별점별 개수 분포를 조회합니다.
 * @summary [공통] 상점 리뷰 통계
 */
export type getReviewStatsResponse200 = {
  data: CommonResponseReviewStatsResponse
  status: 200
}

export type getReviewStatsResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getReviewStatsResponseSuccess = (getReviewStatsResponse200) & {
  headers: Headers;
};
export type getReviewStatsResponseError = (getReviewStatsResponse404) & {
  headers: Headers;
};

export type getReviewStatsResponse = (getReviewStatsResponseSuccess | getReviewStatsResponseError)

export const getGetReviewStatsUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/reviews/stats`
}

export const getReviewStats = async (storeId: number, options?: RequestInit): Promise<getReviewStatsResponse> => {
  
  const res = await fetch(getGetReviewStatsUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getReviewStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReviewStatsResponse
}


