/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateStoreBody,
  GetNearbyStoresParams,
  GetStoresParams,
  StoreReportRequest,
  UpdateStoreBody
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 전체 상점 목록을 페이징하여 조회합니다.
 * @summary [학생] 상점 목록 조회
 */
export type getStoresResponse200 = {
  data: Blob
  status: 200
}
    
export type getStoresResponseSuccess = (getStoresResponse200) & {
  headers: Headers;
};
;

export type getStoresResponse = (getStoresResponseSuccess)

export const getGetStoresUrl = (params: GetStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/stores?${stringifiedParams}` : `/api/stores`
}

export const getStores = async (params: GetStoresParams, options?: RequestInit): Promise<getStoresResponse> => {
  
  return customFetch<getStoresResponse>(getGetStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoresQueryKey = (params?: GetStoresParams,) => {
    return [
    `/api/stores`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStoresQueryOptions = <TData = Awaited<ReturnType<typeof getStores>>, TError = unknown>(params: GetStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStores>>> = ({ signal }) => getStores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getStores>>>
export type GetStoresQueryError = unknown


export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = unknown>(
 params: GetStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores>>,
          TError,
          Awaited<ReturnType<typeof getStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = unknown>(
 params: GetStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStores>>,
          TError,
          Awaited<ReturnType<typeof getStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = unknown>(
 params: GetStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상점 목록 조회
 */

export function useGetStores<TData = Awaited<ReturnType<typeof getStores>>, TError = unknown>(
 params: GetStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 새로운 상점을 등록합니다.
 * @summary [점주] 상점 등록
 */
export type createStoreResponse201 = {
  data: Blob
  status: 201
}

export type createStoreResponse400 = {
  data: Blob
  status: 400
}

export type createStoreResponse403 = {
  data: Blob
  status: 403
}

export type createStoreResponse409 = {
  data: Blob
  status: 409
}
    
export type createStoreResponseSuccess = (createStoreResponse201) & {
  headers: Headers;
};
export type createStoreResponseError = (createStoreResponse400 | createStoreResponse403 | createStoreResponse409) & {
  headers: Headers;
};

export type createStoreResponse = (createStoreResponseSuccess | createStoreResponseError)

export const getCreateStoreUrl = () => {


  

  return `/api/stores`
}

export const createStore = async (createStoreBody: CreateStoreBody, options?: RequestInit): Promise<createStoreResponse> => {
    const formData = new FormData();
if(createStoreBody.images !== undefined) {
 createStoreBody.images.forEach(value => formData.append(`images`, value));
 }
formData.append(`request`, JSON.stringify(createStoreBody.request));

  return customFetch<createStoreResponse>(getCreateStoreUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getCreateStoreMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStore>>, TError,{data: CreateStoreBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStore>>, TError,{data: CreateStoreBody}, TContext> => {

const mutationKey = ['createStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStore>>, {data: CreateStoreBody}> = (props) => {
          const {data} = props ?? {};

          return  createStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStoreMutationResult = NonNullable<Awaited<ReturnType<typeof createStore>>>
    export type CreateStoreMutationBody = CreateStoreBody
    export type CreateStoreMutationError = Blob

    /**
 * @summary [점주] 상점 등록
 */
export const useCreateStore = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStore>>, TError,{data: CreateStoreBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStore>>,
        TError,
        {data: CreateStoreBody},
        TContext
      > => {
      return useMutation(getCreateStoreMutationOptions(options), queryClient);
    }
    /**
 * 특정 상점을 신고합니다.
 * @summary [학생] 상점 신고
 */
export type reportStoreResponse200 = {
  data: Blob
  status: 200
}

export type reportStoreResponse404 = {
  data: Blob
  status: 404
}

export type reportStoreResponse409 = {
  data: Blob
  status: 409
}
    
export type reportStoreResponseSuccess = (reportStoreResponse200) & {
  headers: Headers;
};
export type reportStoreResponseError = (reportStoreResponse404 | reportStoreResponse409) & {
  headers: Headers;
};

export type reportStoreResponse = (reportStoreResponseSuccess | reportStoreResponseError)

export const getReportStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/reports`
}

export const reportStore = async (storeId: number,
    storeReportRequest: StoreReportRequest, options?: RequestInit): Promise<reportStoreResponse> => {
  
  return customFetch<reportStoreResponse>(getReportStoreUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeReportRequest,)
  }
);}




export const getReportStoreMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext> => {

const mutationKey = ['reportStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportStore>>, {storeId: number;data: StoreReportRequest}> = (props) => {
          const {storeId,data} = props ?? {};

          return  reportStore(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReportStoreMutationResult = NonNullable<Awaited<ReturnType<typeof reportStore>>>
    export type ReportStoreMutationBody = StoreReportRequest
    export type ReportStoreMutationError = Blob

    /**
 * @summary [학생] 상점 신고
 */
export const useReportStore = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportStore>>, TError,{storeId: number;data: StoreReportRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportStore>>,
        TError,
        {storeId: number;data: StoreReportRequest},
        TContext
      > => {
      return useMutation(getReportStoreMutationOptions(options), queryClient);
    }
    /**
 * 상점 ID로 상점의 상세 정보를 조회합니다.
 * @summary [학생] 상점 단건 조회
 */
export type getStoreResponse200 = {
  data: Blob
  status: 200
}

export type getStoreResponse404 = {
  data: Blob
  status: 404
}
    
export type getStoreResponseSuccess = (getStoreResponse200) & {
  headers: Headers;
};
export type getStoreResponseError = (getStoreResponse404) & {
  headers: Headers;
};

export type getStoreResponse = (getStoreResponseSuccess | getStoreResponseError)

export const getGetStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const getStore = async (storeId: number, options?: RequestInit): Promise<getStoreResponse> => {
  
  return customFetch<getStoreResponse>(getGetStoreUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreQueryKey = (storeId: number,) => {
    return [
    `/api/stores/${storeId}`
    ] as const;
    }

    
export const getGetStoreQueryOptions = <TData = Awaited<ReturnType<typeof getStore>>, TError = Blob>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStore>>> = ({ signal }) => getStore(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreQueryResult = NonNullable<Awaited<ReturnType<typeof getStore>>>
export type GetStoreQueryError = Blob


export function useGetStore<TData = Awaited<ReturnType<typeof getStore>>, TError = Blob>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore>>,
          TError,
          Awaited<ReturnType<typeof getStore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore<TData = Awaited<ReturnType<typeof getStore>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStore>>,
          TError,
          Awaited<ReturnType<typeof getStore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStore<TData = Awaited<ReturnType<typeof getStore>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 상점 단건 조회
 */

export function useGetStore<TData = Awaited<ReturnType<typeof getStore>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStore>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점을 삭제합니다. (본인 상점만 가능)
 * @summary [점주] 상점 삭제
 */
export type deleteStoreResponse204 = {
  data: Blob
  status: 204
}

export type deleteStoreResponse403 = {
  data: Blob
  status: 403
}

export type deleteStoreResponse404 = {
  data: Blob
  status: 404
}
    
export type deleteStoreResponseSuccess = (deleteStoreResponse204) & {
  headers: Headers;
};
export type deleteStoreResponseError = (deleteStoreResponse403 | deleteStoreResponse404) & {
  headers: Headers;
};

export type deleteStoreResponse = (deleteStoreResponseSuccess | deleteStoreResponseError)

export const getDeleteStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const deleteStore = async (storeId: number, options?: RequestInit): Promise<deleteStoreResponse> => {
  
  return customFetch<deleteStoreResponse>(getDeleteStoreUrl(storeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteStoreMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStore>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStore>>, TError,{storeId: number}, TContext> => {

const mutationKey = ['deleteStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStore>>, {storeId: number}> = (props) => {
          const {storeId} = props ?? {};

          return  deleteStore(storeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStoreMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStore>>>
    
    export type DeleteStoreMutationError = Blob

    /**
 * @summary [점주] 상점 삭제
 */
export const useDeleteStore = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStore>>, TError,{storeId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStore>>,
        TError,
        {storeId: number},
        TContext
      > => {
      return useMutation(getDeleteStoreMutationOptions(options), queryClient);
    }
    /**
 * 상점 정보를 수정합니다. (본인 상점만 가능)
 * @summary [점주] 상점 정보 수정
 */
export type updateStoreResponse200 = {
  data: Blob
  status: 200
}

export type updateStoreResponse403 = {
  data: Blob
  status: 403
}

export type updateStoreResponse404 = {
  data: Blob
  status: 404
}

export type updateStoreResponse409 = {
  data: Blob
  status: 409
}
    
export type updateStoreResponseSuccess = (updateStoreResponse200) & {
  headers: Headers;
};
export type updateStoreResponseError = (updateStoreResponse403 | updateStoreResponse404 | updateStoreResponse409) & {
  headers: Headers;
};

export type updateStoreResponse = (updateStoreResponseSuccess | updateStoreResponseError)

export const getUpdateStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const updateStore = async (storeId: number,
    updateStoreBody: UpdateStoreBody, options?: RequestInit): Promise<updateStoreResponse> => {
    const formData = new FormData();
formData.append(`request`, JSON.stringify(updateStoreBody.request));
if(updateStoreBody.images !== undefined) {
 updateStoreBody.images.forEach(value => formData.append(`images`, value));
 }

  return customFetch<updateStoreResponse>(getUpdateStoreUrl(storeId),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
);}




export const getUpdateStoreMutationOptions = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStore>>, TError,{storeId: number;data: UpdateStoreBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStore>>, TError,{storeId: number;data: UpdateStoreBody}, TContext> => {

const mutationKey = ['updateStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStore>>, {storeId: number;data: UpdateStoreBody}> = (props) => {
          const {storeId,data} = props ?? {};

          return  updateStore(storeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStoreMutationResult = NonNullable<Awaited<ReturnType<typeof updateStore>>>
    export type UpdateStoreMutationBody = UpdateStoreBody
    export type UpdateStoreMutationError = Blob

    /**
 * @summary [점주] 상점 정보 수정
 */
export const useUpdateStore = <TError = Blob,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStore>>, TError,{storeId: number;data: UpdateStoreBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStore>>,
        TError,
        {storeId: number;data: UpdateStoreBody},
        TContext
      > => {
      return useMutation(getUpdateStoreMutationOptions(options), queryClient);
    }
    /**
 * 상점의 통계 데이터(단골 수, 쿠폰 발행/사용 수, 리뷰 수)를 조회합니다.
 * @summary [점주] 상점 통계 조회
 */
export type getStoreStatsResponse200 = {
  data: Blob
  status: 200
}

export type getStoreStatsResponse403 = {
  data: Blob
  status: 403
}

export type getStoreStatsResponse404 = {
  data: Blob
  status: 404
}
    
export type getStoreStatsResponseSuccess = (getStoreStatsResponse200) & {
  headers: Headers;
};
export type getStoreStatsResponseError = (getStoreStatsResponse403 | getStoreStatsResponse404) & {
  headers: Headers;
};

export type getStoreStatsResponse = (getStoreStatsResponseSuccess | getStoreStatsResponseError)

export const getGetStoreStatsUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/stats`
}

export const getStoreStats = async (storeId: number, options?: RequestInit): Promise<getStoreStatsResponse> => {
  
  return customFetch<getStoreStatsResponse>(getGetStoreStatsUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreStatsQueryKey = (storeId: number,) => {
    return [
    `/api/stores/${storeId}/stats`
    ] as const;
    }

    
export const getGetStoreStatsQueryOptions = <TData = Awaited<ReturnType<typeof getStoreStats>>, TError = Blob>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreStatsQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreStats>>> = ({ signal }) => getStoreStats(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getStoreStats>>>
export type GetStoreStatsQueryError = Blob


export function useGetStoreStats<TData = Awaited<ReturnType<typeof getStoreStats>>, TError = Blob>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreStats>>,
          TError,
          Awaited<ReturnType<typeof getStoreStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreStats<TData = Awaited<ReturnType<typeof getStoreStats>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreStats>>,
          TError,
          Awaited<ReturnType<typeof getStoreStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreStats<TData = Awaited<ReturnType<typeof getStoreStats>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 상점 통계 조회
 */

export function useGetStoreStats<TData = Awaited<ReturnType<typeof getStoreStats>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreStats>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreStatsQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점의 정보 및 메뉴 등록 여부를 조회합니다.
 * @summary [점주] 상점 등록 상태 조회
 */
export type getStoreRegistrationStatusResponse200 = {
  data: Blob
  status: 200
}

export type getStoreRegistrationStatusResponse404 = {
  data: Blob
  status: 404
}
    
export type getStoreRegistrationStatusResponseSuccess = (getStoreRegistrationStatusResponse200) & {
  headers: Headers;
};
export type getStoreRegistrationStatusResponseError = (getStoreRegistrationStatusResponse404) & {
  headers: Headers;
};

export type getStoreRegistrationStatusResponse = (getStoreRegistrationStatusResponseSuccess | getStoreRegistrationStatusResponseError)

export const getGetStoreRegistrationStatusUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/registration-status`
}

export const getStoreRegistrationStatus = async (storeId: number, options?: RequestInit): Promise<getStoreRegistrationStatusResponse> => {
  
  return customFetch<getStoreRegistrationStatusResponse>(getGetStoreRegistrationStatusUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreRegistrationStatusQueryKey = (storeId: number,) => {
    return [
    `/api/stores/${storeId}/registration-status`
    ] as const;
    }

    
export const getGetStoreRegistrationStatusQueryOptions = <TData = Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError = Blob>(storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreRegistrationStatusQueryKey(storeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreRegistrationStatus>>> = ({ signal }) => getStoreRegistrationStatus(storeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(storeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreRegistrationStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getStoreRegistrationStatus>>>
export type GetStoreRegistrationStatusQueryError = Blob


export function useGetStoreRegistrationStatus<TData = Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError = Blob>(
 storeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreRegistrationStatus>>,
          TError,
          Awaited<ReturnType<typeof getStoreRegistrationStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreRegistrationStatus<TData = Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreRegistrationStatus>>,
          TError,
          Awaited<ReturnType<typeof getStoreRegistrationStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreRegistrationStatus<TData = Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 상점 등록 상태 조회
 */

export function useGetStoreRegistrationStatus<TData = Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError = Blob>(
 storeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreRegistrationStatus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreRegistrationStatusQueryOptions(storeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 위도, 경도, 반경(km)을 기준으로 주위 상점을 조회합니다.
 * @summary [학생] 주위 상점 조회
 */
export type getNearbyStoresResponse200 = {
  data: Blob
  status: 200
}
    
export type getNearbyStoresResponseSuccess = (getNearbyStoresResponse200) & {
  headers: Headers;
};
;

export type getNearbyStoresResponse = (getNearbyStoresResponseSuccess)

export const getGetNearbyStoresUrl = (params: GetNearbyStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/stores/nearby?${stringifiedParams}` : `/api/stores/nearby`
}

export const getNearbyStores = async (params: GetNearbyStoresParams, options?: RequestInit): Promise<getNearbyStoresResponse> => {
  
  return customFetch<getNearbyStoresResponse>(getGetNearbyStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetNearbyStoresQueryKey = (params?: GetNearbyStoresParams,) => {
    return [
    `/api/stores/nearby`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetNearbyStoresQueryOptions = <TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNearbyStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNearbyStores>>> = ({ signal }) => getNearbyStores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNearbyStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getNearbyStores>>>
export type GetNearbyStoresQueryError = unknown


export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyStores>>,
          TError,
          Awaited<ReturnType<typeof getNearbyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNearbyStores>>,
          TError,
          Awaited<ReturnType<typeof getNearbyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 주위 상점 조회
 */

export function useGetNearbyStores<TData = Awaited<ReturnType<typeof getNearbyStores>>, TError = unknown>(
 params: GetNearbyStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNearbyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNearbyStoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 자신이 등록한 모든 상점을 조회합니다.
 * @summary [점주] 자신의 상점 조회
 */
export type getMyStoresResponse200 = {
  data: Blob
  status: 200
}
    
export type getMyStoresResponseSuccess = (getMyStoresResponse200) & {
  headers: Headers;
};
;

export type getMyStoresResponse = (getMyStoresResponseSuccess)

export const getGetMyStoresUrl = () => {


  

  return `/api/stores/my-stores`
}

export const getMyStores = async ( options?: RequestInit): Promise<getMyStoresResponse> => {
  
  return customFetch<getMyStoresResponse>(getGetMyStoresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyStoresQueryKey = () => {
    return [
    `/api/stores/my-stores`
    ] as const;
    }

    
export const getGetMyStoresQueryOptions = <TData = Awaited<ReturnType<typeof getMyStores>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyStoresQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyStores>>> = ({ signal }) => getMyStores({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getMyStores>>>
export type GetMyStoresQueryError = unknown


export function useGetMyStores<TData = Awaited<ReturnType<typeof getMyStores>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStores>>,
          TError,
          Awaited<ReturnType<typeof getMyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStores<TData = Awaited<ReturnType<typeof getMyStores>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStores>>,
          TError,
          Awaited<ReturnType<typeof getMyStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStores<TData = Awaited<ReturnType<typeof getMyStores>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 자신의 상점 조회
 */

export function useGetMyStores<TData = Awaited<ReturnType<typeof getMyStores>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyStoresQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 학생의 소속 대학에서 이번 주 찜이 가장 많이 늘어난 상점 Top 10을 조회합니다.
 * @summary [학생] 이번 주 핫한 가게 조회
 */
export type getHotStoresResponse200 = {
  data: Blob
  status: 200
}

export type getHotStoresResponse403 = {
  data: Blob
  status: 403
}
    
export type getHotStoresResponseSuccess = (getHotStoresResponse200) & {
  headers: Headers;
};
export type getHotStoresResponseError = (getHotStoresResponse403) & {
  headers: Headers;
};

export type getHotStoresResponse = (getHotStoresResponseSuccess | getHotStoresResponseError)

export const getGetHotStoresUrl = () => {


  

  return `/api/stores/hot`
}

export const getHotStores = async ( options?: RequestInit): Promise<getHotStoresResponse> => {
  
  return customFetch<getHotStoresResponse>(getGetHotStoresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHotStoresQueryKey = () => {
    return [
    `/api/stores/hot`
    ] as const;
    }

    
export const getGetHotStoresQueryOptions = <TData = Awaited<ReturnType<typeof getHotStores>>, TError = Blob>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHotStoresQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHotStores>>> = ({ signal }) => getHotStores({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHotStoresQueryResult = NonNullable<Awaited<ReturnType<typeof getHotStores>>>
export type GetHotStoresQueryError = Blob


export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = Blob>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHotStores>>,
          TError,
          Awaited<ReturnType<typeof getHotStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHotStores>>,
          TError,
          Awaited<ReturnType<typeof getHotStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [학생] 이번 주 핫한 가게 조회
 */

export function useGetHotStores<TData = Awaited<ReturnType<typeof getHotStores>>, TError = Blob>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHotStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHotStoresQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점의 특정 이미지를 삭제합니다.
 * @summary [점주] 상점 이미지 개별 삭제
 */
export type deleteStoreImageResponse200 = {
  data: Blob
  status: 200
}
    
export type deleteStoreImageResponseSuccess = (deleteStoreImageResponse200) & {
  headers: Headers;
};
;

export type deleteStoreImageResponse = (deleteStoreImageResponseSuccess)

export const getDeleteStoreImageUrl = (storeId: number,
    imageId: number,) => {


  

  return `/api/stores/${storeId}/images/${imageId}`
}

export const deleteStoreImage = async (storeId: number,
    imageId: number, options?: RequestInit): Promise<deleteStoreImageResponse> => {
  
  return customFetch<deleteStoreImageResponse>(getDeleteStoreImageUrl(storeId,imageId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteStoreImageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStoreImage>>, TError,{storeId: number;imageId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStoreImage>>, TError,{storeId: number;imageId: number}, TContext> => {

const mutationKey = ['deleteStoreImage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStoreImage>>, {storeId: number;imageId: number}> = (props) => {
          const {storeId,imageId} = props ?? {};

          return  deleteStoreImage(storeId,imageId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStoreImageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStoreImage>>>
    
    export type DeleteStoreImageMutationError = unknown

    /**
 * @summary [점주] 상점 이미지 개별 삭제
 */
export const useDeleteStoreImage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStoreImage>>, TError,{storeId: number;imageId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStoreImage>>,
        TError,
        {storeId: number;imageId: number},
        TContext
      > => {
      return useMutation(getDeleteStoreImageMutationOptions(options), queryClient);
    }
    