/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseListStoreResponse,
  CommonResponseLong,
  CommonResponsePageResponseStoreResponse,
  CommonResponseStoreResponse,
  CommonResponseVoid,
  CreateStoreBody,
  GetStoresParams,
  StoreReportRequest,
  SwaggerErrorResponse,
  UpdateStoreBody
} from './generated.schemas';



/**
 * 전체 상점 목록을 페이징하여 조회합니다.
 * @summary [공통] 상점 목록 조회
 */
export type getStoresResponse200 = {
  data: CommonResponsePageResponseStoreResponse
  status: 200
}
    
export type getStoresResponseSuccess = (getStoresResponse200) & {
  headers: Headers;
};
;

export type getStoresResponse = (getStoresResponseSuccess)

export const getGetStoresUrl = (params: GetStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/stores?${stringifiedParams}` : `/api/stores`
}

export const getStores = async (params: GetStoresParams, options?: RequestInit): Promise<getStoresResponse> => {
  
  const res = await fetch(getGetStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoresResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoresResponse
}


/**
 * 새로운 상점을 등록합니다.
 * @summary [점주] 상점 등록
 */
export type createStoreResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createStoreResponse400 = {
  data: SwaggerErrorResponse
  status: 400
}

export type createStoreResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type createStoreResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type createStoreResponseSuccess = (createStoreResponse201) & {
  headers: Headers;
};
export type createStoreResponseError = (createStoreResponse400 | createStoreResponse403 | createStoreResponse409) & {
  headers: Headers;
};

export type createStoreResponse = (createStoreResponseSuccess | createStoreResponseError)

export const getCreateStoreUrl = () => {


  

  return `/api/stores`
}

export const createStore = async (createStoreBody: CreateStoreBody, options?: RequestInit): Promise<createStoreResponse> => {
  
  const res = await fetch(getCreateStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createStoreResponse
}


/**
 * 특정 상점을 신고합니다.
 * @summary [학생] 상점 신고
 */
export type reportStoreResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type reportStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type reportStoreResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type reportStoreResponseSuccess = (reportStoreResponse200) & {
  headers: Headers;
};
export type reportStoreResponseError = (reportStoreResponse404 | reportStoreResponse409) & {
  headers: Headers;
};

export type reportStoreResponse = (reportStoreResponseSuccess | reportStoreResponseError)

export const getReportStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/reports`
}

export const reportStore = async (storeId: number,
    storeReportRequest: StoreReportRequest, options?: RequestInit): Promise<reportStoreResponse> => {
  
  const res = await fetch(getReportStoreUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeReportRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: reportStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as reportStoreResponse
}


/**
 * 상점 ID로 상점의 상세 정보를 조회합니다.
 * @summary [공통] 상점 단건 조회
 */
export type getStoreResponse200 = {
  data: CommonResponseStoreResponse
  status: 200
}

export type getStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type getStoreResponseSuccess = (getStoreResponse200) & {
  headers: Headers;
};
export type getStoreResponseError = (getStoreResponse404) & {
  headers: Headers;
};

export type getStoreResponse = (getStoreResponseSuccess | getStoreResponseError)

export const getGetStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const getStore = async (storeId: number, options?: RequestInit): Promise<getStoreResponse> => {
  
  const res = await fetch(getGetStoreUrl(storeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoreResponse
}


/**
 * 상점을 삭제합니다. (본인 상점만 가능)
 * @summary [점주] 상점 삭제
 */
export type deleteStoreResponse204 = {
  data: CommonResponseVoid
  status: 204
}

export type deleteStoreResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type deleteStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}
    
export type deleteStoreResponseSuccess = (deleteStoreResponse204) & {
  headers: Headers;
};
export type deleteStoreResponseError = (deleteStoreResponse403 | deleteStoreResponse404) & {
  headers: Headers;
};

export type deleteStoreResponse = (deleteStoreResponseSuccess | deleteStoreResponseError)

export const getDeleteStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const deleteStore = async (storeId: number, options?: RequestInit): Promise<deleteStoreResponse> => {
  
  const res = await fetch(getDeleteStoreUrl(storeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteStoreResponse
}


/**
 * 상점 정보를 수정합니다. (본인 상점만 가능)
 * @summary [점주] 상점 정보 수정
 */
export type updateStoreResponse200 = {
  data: CommonResponseVoid
  status: 200
}

export type updateStoreResponse403 = {
  data: SwaggerErrorResponse
  status: 403
}

export type updateStoreResponse404 = {
  data: SwaggerErrorResponse
  status: 404
}

export type updateStoreResponse409 = {
  data: SwaggerErrorResponse
  status: 409
}
    
export type updateStoreResponseSuccess = (updateStoreResponse200) & {
  headers: Headers;
};
export type updateStoreResponseError = (updateStoreResponse403 | updateStoreResponse404 | updateStoreResponse409) & {
  headers: Headers;
};

export type updateStoreResponse = (updateStoreResponseSuccess | updateStoreResponseError)

export const getUpdateStoreUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}`
}

export const updateStore = async (storeId: number,
    updateStoreBody: UpdateStoreBody, options?: RequestInit): Promise<updateStoreResponse> => {
  
  const res = await fetch(getUpdateStoreUrl(storeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStoreBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateStoreResponse
}


/**
 * 자신이 등록한 모든 상점을 조회합니다.
 * @summary [점주] 자신의 상점 조회
 */
export type getMyStoresResponse200 = {
  data: CommonResponseListStoreResponse
  status: 200
}
    
export type getMyStoresResponseSuccess = (getMyStoresResponse200) & {
  headers: Headers;
};
;

export type getMyStoresResponse = (getMyStoresResponseSuccess)

export const getGetMyStoresUrl = () => {


  

  return `/api/stores/my-stores`
}

export const getMyStores = async ( options?: RequestInit): Promise<getMyStoresResponse> => {
  
  const res = await fetch(getGetMyStoresUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMyStoresResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyStoresResponse
}


/**
 * 상점의 특정 이미지를 삭제합니다.
 * @summary [점주] 상점 이미지 개별 삭제
 */
export type deleteStoreImageResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteStoreImageResponseSuccess = (deleteStoreImageResponse200) & {
  headers: Headers;
};
;

export type deleteStoreImageResponse = (deleteStoreImageResponseSuccess)

export const getDeleteStoreImageUrl = (storeId: number,
    imageId: number,) => {


  

  return `/api/stores/${storeId}/images/${imageId}`
}

export const deleteStoreImage = async (storeId: number,
    imageId: number, options?: RequestInit): Promise<deleteStoreImageResponse> => {
  
  const res = await fetch(getDeleteStoreImageUrl(storeId,imageId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteStoreImageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteStoreImageResponse
}


