/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * LOOKY API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BizVerificationRequest,
  CreateStoreClaimsBody,
  GetStoreClaimsParams,
  SearchUnclaimedStoresParams,
  StoreClaimRejectionRequest
} from './generated.schemas';

import { customFetch } from './mutator';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 사장님이 상점에 대해 소유를 요청하여 심사 대상이 됩니다.
 * @summary [점주] 상점 소유 요청 등록
 */
export type createStoreClaimsResponse200 = {
  data: Blob
  status: 200
}
    
export type createStoreClaimsResponseSuccess = (createStoreClaimsResponse200) & {
  headers: Headers;
};
;

export type createStoreClaimsResponse = (createStoreClaimsResponseSuccess)

export const getCreateStoreClaimsUrl = () => {


  

  return `/api/store-claims`
}

export const createStoreClaims = async (createStoreClaimsBody: CreateStoreClaimsBody, options?: RequestInit): Promise<createStoreClaimsResponse> => {
  
  return customFetch<createStoreClaimsResponse>(getCreateStoreClaimsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreClaimsBody,)
  }
);}




export const getCreateStoreClaimsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: CreateStoreClaimsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: CreateStoreClaimsBody}, TContext> => {

const mutationKey = ['createStoreClaims'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStoreClaims>>, {data: CreateStoreClaimsBody}> = (props) => {
          const {data} = props ?? {};

          return  createStoreClaims(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStoreClaimsMutationResult = NonNullable<Awaited<ReturnType<typeof createStoreClaims>>>
    export type CreateStoreClaimsMutationBody = CreateStoreClaimsBody
    export type CreateStoreClaimsMutationError = unknown

    /**
 * @summary [점주] 상점 소유 요청 등록
 */
export const useCreateStoreClaims = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStoreClaims>>, TError,{data: CreateStoreClaimsBody}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStoreClaims>>,
        TError,
        {data: CreateStoreClaimsBody},
        TContext
      > => {
      return useMutation(getCreateStoreClaimsMutationOptions(options), queryClient);
    }
    /**
 * 사업자등록번호의 유효성을 검증합니다.
 * @summary [점주] 사업자등록번호 유효성 검증
 */
export type verifyBizRegNoResponse200 = {
  data: Blob
  status: 200
}
    
export type verifyBizRegNoResponseSuccess = (verifyBizRegNoResponse200) & {
  headers: Headers;
};
;

export type verifyBizRegNoResponse = (verifyBizRegNoResponseSuccess)

export const getVerifyBizRegNoUrl = () => {


  

  return `/api/biz-reg-no/verify`
}

export const verifyBizRegNo = async (bizVerificationRequest: BizVerificationRequest, options?: RequestInit): Promise<verifyBizRegNoResponse> => {
  
  return customFetch<verifyBizRegNoResponse>(getVerifyBizRegNoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bizVerificationRequest,)
  }
);}




export const getVerifyBizRegNoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo>>, TError,{data: BizVerificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo>>, TError,{data: BizVerificationRequest}, TContext> => {

const mutationKey = ['verifyBizRegNo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyBizRegNo>>, {data: BizVerificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyBizRegNo(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyBizRegNoMutationResult = NonNullable<Awaited<ReturnType<typeof verifyBizRegNo>>>
    export type VerifyBizRegNoMutationBody = BizVerificationRequest
    export type VerifyBizRegNoMutationError = unknown

    /**
 * @summary [점주] 사업자등록번호 유효성 검증
 */
export const useVerifyBizRegNo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyBizRegNo>>, TError,{data: BizVerificationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyBizRegNo>>,
        TError,
        {data: BizVerificationRequest},
        TContext
      > => {
      return useMutation(getVerifyBizRegNoMutationOptions(options), queryClient);
    }
    /**
 * 상점 소유권 요청을 반려합니다.
 * @summary [관리자] 상점 소유권 요청 반려
 */
export type rejectResponse200 = {
  data: Blob
  status: 200
}
    
export type rejectResponseSuccess = (rejectResponse200) & {
  headers: Headers;
};
;

export type rejectResponse = (rejectResponseSuccess)

export const getRejectUrl = (claimId: number,) => {


  

  return `/api/admin/store-claims/${claimId}/reject`
}

export const reject = async (claimId: number,
    storeClaimRejectionRequest: StoreClaimRejectionRequest, options?: RequestInit): Promise<rejectResponse> => {
  
  return customFetch<rejectResponse>(getRejectUrl(claimId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeClaimRejectionRequest,)
  }
);}




export const getRejectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{claimId: number;data: StoreClaimRejectionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{claimId: number;data: StoreClaimRejectionRequest}, TContext> => {

const mutationKey = ['reject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reject>>, {claimId: number;data: StoreClaimRejectionRequest}> = (props) => {
          const {claimId,data} = props ?? {};

          return  reject(claimId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RejectMutationResult = NonNullable<Awaited<ReturnType<typeof reject>>>
    export type RejectMutationBody = StoreClaimRejectionRequest
    export type RejectMutationError = unknown

    /**
 * @summary [관리자] 상점 소유권 요청 반려
 */
export const useReject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reject>>, TError,{claimId: number;data: StoreClaimRejectionRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reject>>,
        TError,
        {claimId: number;data: StoreClaimRejectionRequest},
        TContext
      > => {
      return useMutation(getRejectMutationOptions(options), queryClient);
    }
    /**
 * 상점 소유권 요청을 승인합니다.
 * @summary [관리자] 상점 소유권 요청 승인
 */
export type approveResponse200 = {
  data: Blob
  status: 200
}
    
export type approveResponseSuccess = (approveResponse200) & {
  headers: Headers;
};
;

export type approveResponse = (approveResponseSuccess)

export const getApproveUrl = (claimId: number,) => {


  

  return `/api/admin/store-claims/${claimId}/approve`
}

export const approve = async (claimId: number, options?: RequestInit): Promise<approveResponse> => {
  
  return customFetch<approveResponse>(getApproveUrl(claimId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getApproveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{claimId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{claimId: number}, TContext> => {

const mutationKey = ['approve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approve>>, {claimId: number}> = (props) => {
          const {claimId} = props ?? {};

          return  approve(claimId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ApproveMutationResult = NonNullable<Awaited<ReturnType<typeof approve>>>
    
    export type ApproveMutationError = unknown

    /**
 * @summary [관리자] 상점 소유권 요청 승인
 */
export const useApprove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approve>>, TError,{claimId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof approve>>,
        TError,
        {claimId: number},
        TContext
      > => {
      return useMutation(getApproveMutationOptions(options), queryClient);
    }
    /**
 * 상점 소유권 요청에 관리자 메모를 남깁니다.
 * @summary [관리자] 상점 소유권 요청 관리자 메모 등록 및 수정
 */
export type updateMemoResponse200 = {
  data: Blob
  status: 200
}
    
export type updateMemoResponseSuccess = (updateMemoResponse200) & {
  headers: Headers;
};
;

export type updateMemoResponse = (updateMemoResponseSuccess)

export const getUpdateMemoUrl = (claimId: number,) => {


  

  return `/api/admin/store-claims/${claimId}/memo`
}

export const updateMemo = async (claimId: number,
    updateMemoBody: string, options?: RequestInit): Promise<updateMemoResponse> => {
  
  return customFetch<updateMemoResponse>(getUpdateMemoUrl(claimId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMemoBody,)
  }
);}




export const getUpdateMemoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemo>>, TError,{claimId: number;data: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMemo>>, TError,{claimId: number;data: string}, TContext> => {

const mutationKey = ['updateMemo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMemo>>, {claimId: number;data: string}> = (props) => {
          const {claimId,data} = props ?? {};

          return  updateMemo(claimId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMemoMutationResult = NonNullable<Awaited<ReturnType<typeof updateMemo>>>
    export type UpdateMemoMutationBody = string
    export type UpdateMemoMutationError = unknown

    /**
 * @summary [관리자] 상점 소유권 요청 관리자 메모 등록 및 수정
 */
export const useUpdateMemo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemo>>, TError,{claimId: number;data: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMemo>>,
        TError,
        {claimId: number;data: string},
        TContext
      > => {
      return useMutation(getUpdateMemoMutationOptions(options), queryClient);
    }
    /**
 * 시스템에 등록된 미등록 상점을 이름 또는 주소로 검색합니다.
 * @summary [점주] 미등록 상점 검색
 */
export type searchUnclaimedStoresResponse200 = {
  data: Blob
  status: 200
}
    
export type searchUnclaimedStoresResponseSuccess = (searchUnclaimedStoresResponse200) & {
  headers: Headers;
};
;

export type searchUnclaimedStoresResponse = (searchUnclaimedStoresResponseSuccess)

export const getSearchUnclaimedStoresUrl = (params: SearchUnclaimedStoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/store-claims/search?${stringifiedParams}` : `/api/store-claims/search`
}

export const searchUnclaimedStores = async (params: SearchUnclaimedStoresParams, options?: RequestInit): Promise<searchUnclaimedStoresResponse> => {
  
  return customFetch<searchUnclaimedStoresResponse>(getSearchUnclaimedStoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchUnclaimedStoresQueryKey = (params?: SearchUnclaimedStoresParams,) => {
    return [
    `/api/store-claims/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchUnclaimedStoresQueryOptions = <TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchUnclaimedStoresQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUnclaimedStores>>> = ({ signal }) => searchUnclaimedStores(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchUnclaimedStoresQueryResult = NonNullable<Awaited<ReturnType<typeof searchUnclaimedStores>>>
export type SearchUnclaimedStoresQueryError = unknown


export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUnclaimedStores>>,
          TError,
          Awaited<ReturnType<typeof searchUnclaimedStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUnclaimedStores>>,
          TError,
          Awaited<ReturnType<typeof searchUnclaimedStores>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [점주] 미등록 상점 검색
 */

export function useSearchUnclaimedStores<TData = Awaited<ReturnType<typeof searchUnclaimedStores>>, TError = unknown>(
 params: SearchUnclaimedStoresParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchUnclaimedStores>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchUnclaimedStoresQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 상점 소유권 요청 목록을 조회합니다. status 파라미터로 상태별 조회가 가능합니다.
 * @summary [관리자] 상점 소유권 요청 목록 조회
 */
export type getStoreClaimsResponse200 = {
  data: Blob
  status: 200
}
    
export type getStoreClaimsResponseSuccess = (getStoreClaimsResponse200) & {
  headers: Headers;
};
;

export type getStoreClaimsResponse = (getStoreClaimsResponseSuccess)

export const getGetStoreClaimsUrl = (params: GetStoreClaimsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/admin/store-claims?${stringifiedParams}` : `/api/admin/store-claims`
}

export const getStoreClaims = async (params: GetStoreClaimsParams, options?: RequestInit): Promise<getStoreClaimsResponse> => {
  
  return customFetch<getStoreClaimsResponse>(getGetStoreClaimsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStoreClaimsQueryKey = (params?: GetStoreClaimsParams,) => {
    return [
    `/api/admin/store-claims`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStoreClaimsQueryOptions = <TData = Awaited<ReturnType<typeof getStoreClaims>>, TError = unknown>(params: GetStoreClaimsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoreClaimsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoreClaims>>> = ({ signal }) => getStoreClaims(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoreClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof getStoreClaims>>>
export type GetStoreClaimsQueryError = unknown


export function useGetStoreClaims<TData = Awaited<ReturnType<typeof getStoreClaims>>, TError = unknown>(
 params: GetStoreClaimsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreClaims>>,
          TError,
          Awaited<ReturnType<typeof getStoreClaims>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreClaims<TData = Awaited<ReturnType<typeof getStoreClaims>>, TError = unknown>(
 params: GetStoreClaimsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoreClaims>>,
          TError,
          Awaited<ReturnType<typeof getStoreClaims>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoreClaims<TData = Awaited<ReturnType<typeof getStoreClaims>>, TError = unknown>(
 params: GetStoreClaimsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary [관리자] 상점 소유권 요청 목록 조회
 */

export function useGetStoreClaims<TData = Awaited<ReturnType<typeof getStoreClaims>>, TError = unknown>(
 params: GetStoreClaimsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoreClaims>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoreClaimsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




