/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseLong,
  CommonResponsePageResponseStoreNewsCommentResponse,
  CommonResponsePageResponseStoreNewsResponse,
  CommonResponseStoreNewsResponse,
  CommonResponseVoid,
  CreateStoreNewsBody,
  CreateStoreNewsCommentRequest,
  GetCommentsParams,
  GetStoreNewsListParams,
  UpdateStoreNewsBody
} from './generated.schemas';



/**
 * 가게의 소식 목록을 조회합니다.
 * @summary [공통] 소식 목록 조회
 */
export type getStoreNewsListResponse200 = {
  data: CommonResponsePageResponseStoreNewsResponse
  status: 200
}
    
export type getStoreNewsListResponseSuccess = (getStoreNewsListResponse200) & {
  headers: Headers;
};
;

export type getStoreNewsListResponse = (getStoreNewsListResponseSuccess)

export const getGetStoreNewsListUrl = (storeId: number,
    params: GetStoreNewsListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/stores/${storeId}/news?${stringifiedParams}` : `/api/stores/${storeId}/news`
}

export const getStoreNewsList = async (storeId: number,
    params: GetStoreNewsListParams, options?: RequestInit): Promise<getStoreNewsListResponse> => {
  
  const res = await fetch(getGetStoreNewsListUrl(storeId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoreNewsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoreNewsListResponse
}


/**
 * 가게에 새로운 소식을 등록합니다.
 * @summary [점주] 소식 등록
 */
export type createStoreNewsResponse201 = {
  data: CommonResponseLong
  status: 201
}

export type createStoreNewsResponse403 = {
  data: CommonResponseLong
  status: 403
}

export type createStoreNewsResponse404 = {
  data: CommonResponseLong
  status: 404
}
    
export type createStoreNewsResponseSuccess = (createStoreNewsResponse201) & {
  headers: Headers;
};
export type createStoreNewsResponseError = (createStoreNewsResponse403 | createStoreNewsResponse404) & {
  headers: Headers;
};

export type createStoreNewsResponse = (createStoreNewsResponseSuccess | createStoreNewsResponseError)

export const getCreateStoreNewsUrl = (storeId: number,) => {


  

  return `/api/stores/${storeId}/news`
}

export const createStoreNews = async (storeId: number,
    createStoreNewsBody: CreateStoreNewsBody, options?: RequestInit): Promise<createStoreNewsResponse> => {
  
  const res = await fetch(getCreateStoreNewsUrl(storeId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreNewsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createStoreNewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createStoreNewsResponse
}


/**
 * 소식에 좋아요를 누르거나 취소합니다.
 * @summary [공통] 소식 좋아요 토글
 */
export type toggleLikeResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type toggleLikeResponseSuccess = (toggleLikeResponse200) & {
  headers: Headers;
};
;

export type toggleLikeResponse = (toggleLikeResponseSuccess)

export const getToggleLikeUrl = (newsId: number,) => {


  

  return `/api/store-news/${newsId}/likes`
}

export const toggleLike = async (newsId: number, options?: RequestInit): Promise<toggleLikeResponse> => {
  
  const res = await fetch(getToggleLikeUrl(newsId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: toggleLikeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as toggleLikeResponse
}


/**
 * 소식의 댓글 목록을 조회합니다.
 * @summary [공통] 댓글 목록 조회
 */
export type getCommentsResponse200 = {
  data: CommonResponsePageResponseStoreNewsCommentResponse
  status: 200
}
    
export type getCommentsResponseSuccess = (getCommentsResponse200) & {
  headers: Headers;
};
;

export type getCommentsResponse = (getCommentsResponseSuccess)

export const getGetCommentsUrl = (newsId: number,
    params: GetCommentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/store-news/${newsId}/comments?${stringifiedParams}` : `/api/store-news/${newsId}/comments`
}

export const getComments = async (newsId: number,
    params: GetCommentsParams, options?: RequestInit): Promise<getCommentsResponse> => {
  
  const res = await fetch(getGetCommentsUrl(newsId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCommentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCommentsResponse
}


/**
 * 소식에 댓글을 작성합니다.
 * @summary [공통] 댓글 작성
 */
export type createCommentResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type createCommentResponseSuccess = (createCommentResponse200) & {
  headers: Headers;
};
;

export type createCommentResponse = (createCommentResponseSuccess)

export const getCreateCommentUrl = (newsId: number,) => {


  

  return `/api/store-news/${newsId}/comments`
}

export const createComment = async (newsId: number,
    createStoreNewsCommentRequest: CreateStoreNewsCommentRequest, options?: RequestInit): Promise<createCommentResponse> => {
  
  const res = await fetch(getCreateCommentUrl(newsId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createStoreNewsCommentRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createCommentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createCommentResponse
}


/**
 * 소식 상세 정보를 조회합니다.
 * @summary [공통] 소식 상세 조회
 */
export type getStoreNewsResponse200 = {
  data: CommonResponseStoreNewsResponse
  status: 200
}
    
export type getStoreNewsResponseSuccess = (getStoreNewsResponse200) & {
  headers: Headers;
};
;

export type getStoreNewsResponse = (getStoreNewsResponseSuccess)

export const getGetStoreNewsUrl = (newsId: number,) => {


  

  return `/api/store-news/${newsId}`
}

export const getStoreNews = async (newsId: number, options?: RequestInit): Promise<getStoreNewsResponse> => {
  
  const res = await fetch(getGetStoreNewsUrl(newsId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoreNewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoreNewsResponse
}


/**
 * 소식을 삭제합니다.
 * @summary [점주] 소식 삭제
 */
export type deleteStoreNewsResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteStoreNewsResponseSuccess = (deleteStoreNewsResponse200) & {
  headers: Headers;
};
;

export type deleteStoreNewsResponse = (deleteStoreNewsResponseSuccess)

export const getDeleteStoreNewsUrl = (newsId: number,) => {


  

  return `/api/store-news/${newsId}`
}

export const deleteStoreNews = async (newsId: number, options?: RequestInit): Promise<deleteStoreNewsResponse> => {
  
  const res = await fetch(getDeleteStoreNewsUrl(newsId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteStoreNewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteStoreNewsResponse
}


/**
 * 소식을 수정합니다.
 * @summary [점주] 소식 수정
 */
export type updateStoreNewsResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type updateStoreNewsResponseSuccess = (updateStoreNewsResponse200) & {
  headers: Headers;
};
;

export type updateStoreNewsResponse = (updateStoreNewsResponseSuccess)

export const getUpdateStoreNewsUrl = (newsId: number,) => {


  

  return `/api/store-news/${newsId}`
}

export const updateStoreNews = async (newsId: number,
    updateStoreNewsBody: UpdateStoreNewsBody, options?: RequestInit): Promise<updateStoreNewsResponse> => {
  
  const res = await fetch(getUpdateStoreNewsUrl(newsId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStoreNewsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateStoreNewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateStoreNewsResponse
}


/**
 * 자신의 댓글을 삭제합니다.
 * @summary [공통] 댓글 삭제
 */
export type deleteCommentResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteCommentResponseSuccess = (deleteCommentResponse200) & {
  headers: Headers;
};
;

export type deleteCommentResponse = (deleteCommentResponseSuccess)

export const getDeleteCommentUrl = (newsId: number,
    commentId: number,) => {


  

  return `/api/store-news/${newsId}/comments/${commentId}`
}

export const deleteComment = async (newsId: number,
    commentId: number, options?: RequestInit): Promise<deleteCommentResponse> => {
  
  const res = await fetch(getDeleteCommentUrl(newsId,commentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCommentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCommentResponse
}


