/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * NEARDEAL API Server
 * API 명세서
 * OpenAPI spec version: v1.0.0
 */
import type {
  CommonResponseListUniversityResponse,
  CommonResponseLong,
  CommonResponseVoid,
  CreateUniversityRequest,
  UpdateUniversityRequest
} from './generated.schemas';



/**
 * 전체 대학 목록을 조회합니다.
 * @summary [공통] 대학 목록 조회
 */
export type getUniversitiesResponse200 = {
  data: CommonResponseListUniversityResponse
  status: 200
}
    
export type getUniversitiesResponseSuccess = (getUniversitiesResponse200) & {
  headers: Headers;
};
;

export type getUniversitiesResponse = (getUniversitiesResponseSuccess)

export const getGetUniversitiesUrl = () => {


  

  return `/api/universities`
}

export const getUniversities = async ( options?: RequestInit): Promise<getUniversitiesResponse> => {
  
  const res = await fetch(getGetUniversitiesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUniversitiesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUniversitiesResponse
}


/**
 * 새로운 대학을 등록합니다.
 * @summary [관리자] 대학 등록
 */
export type createUniversityResponse200 = {
  data: CommonResponseLong
  status: 200
}
    
export type createUniversityResponseSuccess = (createUniversityResponse200) & {
  headers: Headers;
};
;

export type createUniversityResponse = (createUniversityResponseSuccess)

export const getCreateUniversityUrl = () => {


  

  return `/api/universities`
}

export const createUniversity = async (createUniversityRequest: CreateUniversityRequest, options?: RequestInit): Promise<createUniversityResponse> => {
  
  const res = await fetch(getCreateUniversityUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUniversityRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createUniversityResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUniversityResponse
}


/**
 * 대학을 삭제합니다.
 * @summary [관리자] 대학 삭제
 */
export type deleteUniversityResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type deleteUniversityResponseSuccess = (deleteUniversityResponse200) & {
  headers: Headers;
};
;

export type deleteUniversityResponse = (deleteUniversityResponseSuccess)

export const getDeleteUniversityUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}`
}

export const deleteUniversity = async (universityId: number, options?: RequestInit): Promise<deleteUniversityResponse> => {
  
  const res = await fetch(getDeleteUniversityUrl(universityId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteUniversityResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUniversityResponse
}


/**
 * 대학 정보를 수정합니다.
 * @summary [관리자] 대학 수정
 */
export type updateUniversityResponse200 = {
  data: CommonResponseVoid
  status: 200
}
    
export type updateUniversityResponseSuccess = (updateUniversityResponse200) & {
  headers: Headers;
};
;

export type updateUniversityResponse = (updateUniversityResponseSuccess)

export const getUpdateUniversityUrl = (universityId: number,) => {


  

  return `/api/universities/${universityId}`
}

export const updateUniversity = async (universityId: number,
    updateUniversityRequest: UpdateUniversityRequest, options?: RequestInit): Promise<updateUniversityResponse> => {
  
  const res = await fetch(getUpdateUniversityUrl(universityId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUniversityRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateUniversityResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUniversityResponse
}


